### ISSUE TITLE
Need flow design help - have issues and questions

### ISSUE THREAD

**Issue by begunfx** [HaveAGitGat/Tdarr#1007]
**Describe the bug**
I setup a flow with the following goals:

- Run a health check
- Remove subtitles
- Remove closed-captions
- Image removal
- Reorder streams
- Remove any additional data streams
- Check the video resolution - if greater than 1080p then resize to 1080p
- Set the bitrate to 4000
- If the video was resized the append 1080p to the end of the filename
- If the file failed at multiple checkpoints then move to a failed output folder
- Otherwise move to an appropriate output folder

Here's my exported flow:
[Clean Resize ReTranscode v05.txt](https://github.com/HaveAGitGat/Tdarr/files/15380302/Clean.Resize.ReTranscode.v05.txt)

Here are the issues and questions:

1. I have a renameFile node in the flow but it doesn't seem to rename the file when it is passed through this part of the flow.  Am I doing something wrong?  I was using several of the Big Bunny sample files.  Using this file as an example: 
sample__2160__libx264__ac3__30s__video.mkv.  Also, this file seemed to skip transcoding.   Is it because the file is already below 4000 bitrate?  I'm not seeing this detail anywhere.

2. I also got some errors/fails on a few of the sample videos, but am not sure why.  I attached their reports here:
[cM89QiO_W2-log.txt](https://github.com/HaveAGitGat/Tdarr/files/15380287/cM89QiO_W2-log.txt)

3. I would like to remove additional audio channels and only maintain the best multi-channel stream.  What is the best way to do that/include in the flow?

Thanks!

**Comment by HaveAGitGat** [comment]
Hi, for the rename/transcode please post the job report if possible, all details should be in there:
https://docs.tdarr.io/docs/other/job-reports

In the errored log it's failing because you've told it to fail the flow if the new file is larger than the old one. The new file is 20MB and the old one is 16MB.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/86b5f04f-c5f4-447f-8ed3-257f9f73dbda)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/98fd4806-c712-48c3-8964-1a14e99de627)

I've added some additional logging to the compare size plugin:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/642

Also I would not do this:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/d2701cef-424b-4131-9523-8a2d54803a7f)

When a plugin fails, the error handle continues with the file that went into the plugin (as most likely no output file has been produced). So there you are moving the original file into the failed output folder which I'm not sure is what you want.

Please use the plugins repo or Discord for all plugins related issues thanks:
https://github.com/HaveAGitGat/Tdarr_Plugins

**Comment by begunfx** [comment]
Thanks @HaveAGitGat for the response and info.  Sorry, will post in the future in the plugin repo/discord discussion group.   I'll follow up on the rename issue in the plugin repo.
