### ISSUE TITLE
api/v2/get-client-db broken

### ISSUE THREAD

**Issue by DerGuntha** [HaveAGitGat/Tdarr#1065]
Stopped working after update from 2.22.01 to 2.24.05

curl --request POST --url http://localip:port/api/v2/get-client-db --header 'accept: application/json'
returns  "Cannot POST /api/v2/get-client-db"

**Comment by HaveAGitGat** [comment]
Hi this is an old endpoint (same with `export-csv` that was also removed) that Tdarr hasn't used in 2-3 years and causes issues with large libraries due to it returning so much data (can crash the server if there's too much data to return) so was removed in 2.24.01, which improved performance for large libraries, to prevent accidental use.

You can view the api docs at `http://localhost:8266/api-docs/`.

The API docs are also available at https://tdarr.readme.io/ but after the next update this will just say to go to `http://localhost:8266/api-docs/` for API info for the current running Tdarr version.

I wouldn't usually remove an API endpoint but removed these two because of the crashes they can cause with large amounts of data.

For the last few years Tdarr has performed the functionality of those 2 endpoints in a better way using `api/v2/client/{clientType}`. It returns an array of files and the total count:

`{"array":[],"totalCount":0}`

Here are some examples for the status tables at the bottom of the Tdarr tab. `table0` through `table6` represent the tables from left to right. So `table0` is the `Hold` table and `table6` is the `Health Check: Error/Cancelled` table. 

Get all data from `table0` which is the `Hold` table:

```
curl -X POST http://localhost:8266/api/v2/client/status-tables \
-H "Content-Type: application/json" \
-d '{
    "data": {
        "start": 0,
        "pageSize": 100,
        "filters": [],
        "sorts": [],
        "opts": {
            "table": "table0"
        }
    }
}'
```

Get all data from `table1` which is the `Transcode Queue` table:

```
curl -X POST http://localhost:8266/api/v2/client/status-tables \
-H "Content-Type: application/json" \
-d '{
    "data": {
        "start": 0,
        "pageSize": 100,
        "filters": [],
        "sorts": [],
        "opts": {
            "table": "table1"
        }
    }
}'
```

Get filtered and sorted data from `table1` which is the `Transcode Queue` table:

```
curl -X POST http://localhost:8266/api/v2/client/status-tables \
-H "Content-Type: application/json" \
-d '{
    "data": {
        "start": 0,
        "pageSize": 100,
        "filters": [
                {
                    "id": "file",
                    "value": "example"
                },
                {
                    "id": "video_codec_name",
                    "value": "hevc"
                }
     
        ],
        "sorts": [
            {
                "id": "file",
                "desc": false
            }
        ],
        "opts": {
            "table": "table1"
        }
    }
}'
```


Get all staged items:

```
curl -X POST http://localhost:8266/api/v2/client/staged \
-H "Content-Type: application/json" \
-d '{
    "data": {
        "start": 0,
        "pageSize": 100,
        "filters": [],
        "sorts": [],
        "opts": {}
    }
}'
```

Search all items using a filter:

```
curl -X POST http://localhost:8266/api/v2/client/search \
-H "Content-Type: application/json" \
-d '{
    "data": {
        "start": 0,
        "pageSize": 100,
        "filters": [
            {
                "id": "file",
                "value": "example filename"
            },
        ],
        "sorts": [],
        "opts": {}
    }
}'
```

So you can filter, sort and safely return small amounts of paginated data or put the `pageSize` at something like `10000000` to return all data.

To return a csv format just add the `csv` option:

```
curl -X POST http://localhost:7266/api/v2/client/status-tables \
-H "Content-Type: application/json" \
-d '{
    "data": {
        "start": 0,
        "pageSize": 100,
        "filters": [
  
                {
                    "id": "video_codec_name",
                    "value": "hevc"
                }
     
        ],
        "sorts": [
            {
                "id": "file",
                "desc": false
            }
        ],
        "opts": {
            "table": "table1",
            "csv": true
        }
    }
}'
```

`{"csv":";","totalCount":0}`

I'll update the release notes to mention this change.

**Comment by DerGuntha** [comment]
Thx a lot for the fast reply !

**Comment by HaveAGitGat** [comment]
Welcome :)
