### ISSUE TITLE
Why does Tdarr auto pause randomly?

### ISSUE THREAD

**Issue by CurlyFlow** [HaveAGitGat/Tdarr#1069]
Hi,

first, again thanks for your hard work and passion.

So ive set auto pause if cache is >500gb.

I couldnt see anything in the logs related to beeing stopped because of hitting that limit. The node is just paused and i can unpause it, but i would like to make that process as automatic as possible without needing to unpause every day.

TLDR: I would like to know why the nodes auto pause once a day.

Thats the node log.
[oBoNYV3jH-log (1).txt](https://github.com/user-attachments/files/16781548/oBoNYV3jH-log.1.txt)
[Tdarr_Server_Log.txt](https://github.com/user-attachments/files/16781558/Tdarr_Server_Log.txt)
[Tdarr_Node_Log.txt](https://github.com/user-attachments/files/16781560/Tdarr_Node_Log.txt)

Do you need anything else to look into this problem?

**Comment by HaveAGitGat** [comment]
There are only 3 ways to pause the nodes:

- From the UI on the Tdarr tab
- Automatically using the `Auto pause nodes if cache full` option on the `Options` tab
- Using the `Pause/Unpause All Nodes` flow plugin.

Your server log only keeps the last 1MB of logs so if it's auto paused due to the cache having less space free than the threshold then it would have happened earlier on. If you check it when it happens it should show log warning `Cache full for library "xxx" ... Pausing all nodes`.

Tdarr will auto pause if the space left on the cache disk is less than the `Cache Threshold`. So you're setting it to auto pause if there's less than 500GB free space left.

```
Auto pause nodes if cache full

Enable this option to auto pause all nodes if one of your library caches if full. Set the threshold below in gigabytes. For example if '20' is set, all nodes will pause if the cache has less than 20GB free.
```

**Comment by HaveAGitGat** [comment]
> So ive set auto pause if cache is >500gb.

Ok was just saying that because you said you've set it up so that it will pause if the cache is `greater` than 500GB but that's not how it works. Putting `500` in means it will pause if there's less than 500GB of free space, not if the cache size greater than 500GB.

It runs every 60 seconds and if the free space on the cache disk is less than the amount specified, it pauses all nodes.

There's currently no option to change the log size directly in Tdarr but many container managers such as portainer allow you to set the containers log size e.g. https://docs.portainer.io/user/docker/containers/logs in case you are using something like that.

You can have it send a discord notification when the cache is full if you have Pro:
![image](https://github.com/user-attachments/assets/a0c0a7a3-8011-4a4c-b251-eddcc469d1d6)

If all is setup correctly then it could be that the free space being given to Tdarr is not the real amount of free space but will need to add some extra logging for that.

When it pauses the nodes you'll get a log like this:

```
 [WARN] Tdarr_Server - Cache full for library "Library Name 1": C:/storage/C/Transcode/Cache Folder. Free space: 69.21 GB. Threshold: 100 GB. Pausing all nodes. Time taken: 723 ms.
```

**Comment by HaveAGitGat** [comment]
No it will repeat each minute. Is your cache on a network or multi drive array? Could be that the cache location is temporarily becoming smaller. Or do you have anyone else using Tdarr who is pausing them?

Auto unpausing nodes in this case is not right because if someone pauses their nodes then they don't want them being constantly unpaused if the cache isn't full.

**Comment by HaveAGitGat** [comment]
I've added config `maxLogSize` for next version, so you can set it at e.g. `104857600` bytes which is 100MB to keep a larger log. I've increased the default from 1MB to 10MB

**Comment by HaveAGitGat** [comment]
@CurlyFlow sorry for the delay, was working on some API/network issues for 2.25.01 just released. It has `maxLogSizeMB` which defaults to 10 so will show much more logs for you but can increase to e.g. 100.

Tdarr does not auto unpause all nodes. It only auto pauses atm and it only does that when it detects free disk space is less than the specified threshold.

Try the latest version and if it happens again we can check the logs ty.
