### ISSUE TITLE
[Feature request] Exclude from library by filename/extension

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#109]
On the Library Source, we can currently ignore a specific sub-folder. It would be useful to be able to ignore by filename/extension string as well.

For instance, the string "-trailer" could ignore any files that include the `-trailer` line in the filename. The string ".avi" could ignore any files that end in `.avi` as an example. For whatever purpose the library creator(s) would need really.

**Comment by HaveAGitGat** [comment]
To ignore file extensions such as '.avi' you can just remove 'avi' from the container types to scan for:

![image](https://user-images.githubusercontent.com/43864057/72622361-f2a4e280-393a-11ea-85b0-1bcf1aad2bbc.png)

The way the 'Sub-folders to ignore' option works is it checks if the full filepath contains any of the substrings entered in the input box. It doesn't specifically check sub-folders.

So to ignore 'avi' and 'trailer' you can put the following in the input box:

![image](https://user-images.githubusercontent.com/43864057/72622922-1583c680-393c-11ea-871e-f6d25462909b.png)

I'll amend the Tdarr wording so that this is explained :).

**Comment by HaveAGitGat** [comment]
Available in 1.102
