### ISSUE TITLE
UI holding FF browser hostage

### ISSUE THREAD

**Issue by quadcom** [HaveAGitGat/Tdarr#1096]
v2.26.01

Not sure how or why, but using FF, Tdarr seems to hold the browser hostage. If Tdarr is showing and you try to click on a browser bookmark, Tdarr refreshes. It will not let you go to any other URL unless you close the browser window. Even typing a new URL in the address bar triggers a browser refresh of Tdarr.

While this might not be a Tdarr specific issue. I have not experienced this with any other site; locally hosted or remote. I also cannot replicate this in Chrome but I can replicate it in a FF incognito window.

Has anyone run into this before or seen this behaviour with Tdarr or any other site?

**Comment by dennix85** [comment]
Since it is not happening in chrome, i call for a FF issue not a tdarr issue, 
do you have some extensions or plugins running in FF perhaps interfering ?

**Comment by quadcom** [comment]
That's what I had thought, which is why I ran it incognito (no add-ons running). 

I don't know, FF is apparently doing some questionable sh!t lately with their releases. 

I just thought I would pop it up here in the event someone else runs into the same thing and figures out what's going on. Like I wrote, I haven't seen this before, and it only happens on Tdarr.

**Comment by HaveAGitGat** [comment]
Tdarr uses websockets between the browser and server. If the websocket disconnects, the browser is set to refresh so that it can connect and reload everything again. On chrome this works fine but in Firefox when you try to go to a new URL, the Tdarr web socket disconnect refreshes the page and for some reason Firefox have made this override you going to the new URL. So the page just keeps refreshing when you try to leave. I think someone reported this to Firefox a few years ago but it has not been fixed yet.

I've added a fix for the next version.
