### ISSUE TITLE
Don't use AI for promotional splash image upon opening web interface

### ISSUE THREAD

**Issue by ellitedev** [HaveAGitGat/Tdarr#1136]
**Is your feature request related to a problem? Please describe.**
I consider AI generated art a problem, yes.

**Describe the solution you'd like**
Make something yourself or hire an artist.

**Describe alternatives you've considered**
Running my own ffmpeg scripts.

**Additional context**
This takes up the entire screen. It's insane.
![image](https://github.com/user-attachments/assets/d999ca15-70f5-4ecf-b085-3b7707bafd1a)

**Comment by dennix85** [comment]
Consider getting the pro version.
That will get rid of the problem.
Or just press the x button and it will go away..
xD

**Comment by HaveAGitGat** [comment]
Hi, you just need to press the ‘X’ button in the top right to close the notification. The size of the image is the same as previous notifications over the years which I’ve never received any issue for. There are typically only 3 notifications per year which is not very many. 

In terms of AI art it’s just meant to be a fun winter sale image (it’s the same one as last year because I quite liked it) and I’m just one guy (and not an artist). I do work with graphic artists every now and then but it can be quite hit and miss; sometimes going back and forth for 2 weeks for an end result that doesn’t look very good and is just money down the drain which has happened a few times. But I’ll look for some improvements for the next one thanks.

**Comment by HaveAGitGat** [comment]
There’s also the issue that there are many people offering services as “graphic artists” these days but they are just using the same AI tools.

No doubt if I signed up for Adobe suite and used their AI tools I’d be able to quickly make a non-AI looking graphic which you would not have raised an issue with. I would in that case be the “artist”. But financially all this means is that instead of paying a tiny bit money to an AI company directly, I’d have paid a much larger sum of money to Adobe (a company many are not fond of), who then pass the money on to whatever AI services they integrate.

Interesting.
