### ISSUE TITLE
Unwanted workers created at launch

### ISSUE THREAD

**Issue by Xe138** [HaveAGitGat/Tdarr#119]
At launch, Tdarr creates more workers than it is configured for.  The worker count returns to expected numbers after completion of jobs.

Configure Tdarr to run 1 Transcode worker and 2 Health check workers.
Ensure there is a queue of transcode jobs ready
Restart Tdarr

With the above configuration, Tdarr should launch a single Transcode worker.

![Workers](https://user-images.githubusercontent.com/50377201/71624312-d7eb1380-2baf-11ea-877c-6e7756894b6e.PNG)

 - OS: unRAID 6.8.0 (Docker 19.03.5)
 - Browser: Chrome 79.0.3945.88
 - Tdarr Version: Beta 1.101

**Comment by marshalleq** [comment]
I’ve had this too. It seemed to be when you had a higher number of workers, then reduced them to a lower number, even after restart it would try to finish the number previously set first.

**Comment by HaveAGitGat** [comment]
@Xe138 okay thanks.

I thought this issue was resolved previously but I will take another look.

**Comment by HaveAGitGat** [comment]
The issue is to do with lag between server and workers when lots of workers are being started up (3+ it seems, depending on system).

I've made some changes which should fix this in 1.103. Haven't been able to reproduce/force the issue on it.

@marshalleq I think yours is a different issue although let me know if you encounter it in 1.103.
