### ISSUE TITLE
Duplicate encoding jobs when output folder is used

### ISSUE THREAD

**Issue by Xe138** [HaveAGitGat/Tdarr#124]
Files are encoded multiple times when output folder is used.  After a file is successfully encoded to an output folder, a new job is sometimes generated to encode the original file again.

Occurs with output folder set outside of scanned library and with the queue sorted by "newest".

Tdarr should check if a successfully encoded file exists in the output folder when evaluating if a source file should be encoded.

 - OS: UnRAID 6.8.0
 - Browser: Chrome
 - Version: Tdarr Beta 1.101

I have changed the queue sorting to "largest" and will monitor to see if the issue persists.  I have not been able to determine if the issue is caused by the original file being re-added to the queue after completion or if the job is simply restarting.

**Comment by azcom** [comment]
@Xe138 I also noticed this behaviour back in november but I think it got lost as I stupidly didn't post the information under it's own issue.

https://github.com/HaveAGitGat/Tdarr/issues/1#issuecomment-559535719

Unless/Until we have integration with Sonarr/Radarr to tell them to process/import the newly transcoded files for us automatically (so they get scanned & renamed with the new codec as I need them to because I include it in my file names) I need to set an output folder outside of the source folder so I can then do a manual import with Sonarr/Radarr to get the file names corrected.

With this current behaviour I can't even do it this way because it keeps transcoding files over and over again before I get to importing them, wasting valuable processing time by repeating the same work multiple times and blocking up the queue etc. This is presumably because the source file is still meeting all the criteria of the plugin/filters and it isn't checking the output folder for the presence of that file name before starting the encode again.

If there was a simple built in filter that every queue item went through that works something like:

IF 'manual output folder selected' THEN 'check for source file name in output folder' AND-IF 'source file name is present'  THEN 'transcode not required' BUT-IF 'source file name is not present' THEN 'transcode'.

Hopefully that would be fairly simple to implement?

**Comment by marshalleq** [comment]
Theoretically, if you encode the file in place (i'e don't use the manual output folder method), Radarr at least can rename the file on scan after detecting the new file info.  However, in my short test, Radarr does detect the new codec, but doesn't yet rename the file.  Not sure why.  Anyway, thought this might help with another option while the above is resolved.

**Comment by aiorus** [comment]
In my experience, it will add to the queue the file from the output directory, not the original file. Maybe that is where the issue is coming from.

**Comment by aiorus** [comment]
Any updates on this issue? It's still present in v1.108

**Comment by HaveAGitGat** [comment]
@aiorus I think you are referring to a different issue to the others.

What you describe is expected behaviour when using a plugin stack with an output folder as mentioned in the output folder notes:

With plugins:

Plugin 1: Source ---> Cache ---> Output

Plugin 2: Output ---> Cache ---> Output

Plugin 3: Output ---> Cache ---> Output

etc

**Comment by aiorus** [comment]
ok, let me explain my issue.

I have 2 filters in my chain, one for set the correct order in the tracks for the video, and the next one to encode if it's not in h265. I understand if it shows multiple times, but only one time it's a real encode, the other one is a check.

However, every time there is a new file in the folder, multiple (already processed) files get queued, so it can be encoding for the whole day multiple files, multiple times, over one new entry.

Let me know what I can do to help with this issue.

Thanks for a GREAT system.

**Comment by aiorus** [comment]
Any kind of updates on this issue?

**Comment by HaveAGitGat** [comment]
Hi, sorry I have not made any changes to this. The best way to use Tdarr in this manner is to leave the output option off and copy files into your Tdarr library source folder. Tdarr will then process the files as normal and you can then move the files once done. A small script should be able to do this automatically. Not ideal but should do the job.

**Comment by HaveAGitGat** [comment]
@azcom v2 does all plugin transcoding in the cache before copying the library or output folder. Should fix your issue.

@Xe138 v2 keeps a history of already transcoded files. To re-transcode a file, you need to clear the history:

![image](https://user-images.githubusercontent.com/43864057/105863569-4daef200-5ff1-11eb-900f-ee0b40aec5d6.png)

Or you can delete a specific file in the database history:
![image](https://user-images.githubusercontent.com/43864057/105863714-759e5580-5ff1-11eb-9068-93d5229df8e1.png)

@aiorus  please try v2:

http://tdarr.io/docs/installation

Reopen this if needed
