### ISSUE TITLE
[Feature Request] ffmpeg compiled with lib_npp to support GPU scaling

### ISSUE THREAD

**Issue by CplPwnies** [HaveAGitGat/Tdarr#125]
2019-12-16: Please note I'm on a 2 week break. Sorry for the inconvenience.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I am using the tdarr_aio docker container. It works great, but I would just like to request a version of ffmpeg that is compiled to support libnpp so we can do hardware scaling instead of CPU scaling when resizing videos.

**Describe alternatives you've considered**
N/A

**Additional context**
I am using nvenc to re-encode my library to HEVC, and at the same time, I am resizing all my TV episodes from 1080p -> 720p (just personal preference). Currently, in my plugin, I have to define the option `-vf scale=-1:720`. This is CPU based scaling, and I would like to speed up the process by using GPU scaling, but the current version of ffmpeg in the container that support nvenc is not compiled with libnpp support.

Example of command line option for GPU scaling: `-vf scale_npp=w=1280:h=720:interp_algo=lanczos`

In previous testing this has taken conversion times from 1hr -> 5 minutes.

**Comment by HaveAGitGat** [comment]
Okay I'll have a look once I've dealt with some bugs and older feature requests.

**Comment by HaveAGitGat** [comment]
Thought this would be a simple case of just adding --enable-libnpp to the config but CUDA also needs to be installed for ffmpeg to even start up. CUDA will blow up the container size by a GB or 2 so might put this in an experimental container.

**Comment by MasterChiefmas** [comment]
I had been looking at building ffmpeg myself a few years back with CUDA support. I thought I had read somewhere at one point that nVidia licensing in the libraries prevented most projects from distributing pre-compiled support for CUDA, which is why you didn't see that just out there already. 
This StackExchange post talks about it:
https://stackoverflow.com/questions/55687189/how-to-use-gpu-to-accelerate-the-processing-speed-of-ffmpeg-filter/55747785#55747785
It doesn't call out licensing specifically, but I noticed that one of the build switches they call out is "--enable-nonfree" which if you search on that, leads to a set of posts that I think amount to, if you compile CUDA support in, you can't distribute the binary (GPL/nVidia licensing conflict?)

**Comment by CplPwnies** [comment]
@MasterChiefmas I believe you can still distribute the binary if **--enable-nonfree** is set as a build switch. I subscribe to a debian media repository that has a compiled version of ffmpeg with this enabled.

**Comment by HaveAGitGat** [comment]
Using JellyFin FFmpeg these days so just using what they put in. Might be easiest to use your own version which you can set using ffmpegPath in an env variable in V2.
