### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by Viceman256** [HaveAGitGat/Tdarr#126]
2019-12-16: Please note I'm on a 2 week break. Sorry for the inconvenience.

**Describe the bug**
 I've just installed Tdarr on Windows (non-docker). If I transcode 2+ files, with general or transcode workers (not entirely sure what a worker is in this context as well but appears to be how many concurrent transcodes?), maxes my CPU to 100%.

The CPU I have is a Ryzen 9 3900x, so it's not easy to max out. Is this expected, or what can I do to avoid having my CPU run at full power for several hours straight?

**To Reproduce**
Transcode

**Expected behavior**
Transcoding with low CPU priority

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome, Firefox, Edge
 - Version 1.101

**Comment by HaveAGitGat** [comment]
Yes that's expected. HandBrake and FFmpeg are multi-threaded applications so I would not be surprised by this. 

Have you tried using only one transcode worker and flicking the following switch on?

![image](https://user-images.githubusercontent.com/43864057/72626868-5fbc7600-3943-11ea-8750-c5929a78112f.png)

That will prioritise other processes over the Tdarr transcode processes.

**Comment by Viceman256** [comment]
Thank you for your quick reply. It does appear one transcode worker will restrict CPU usage to around 80%. I was just surprised, I'm new to this, and I have a Plex server but when it comes to video encoding and transcoding I'm a bit of a novice. 

When my Plex server transcodes, I could have 4 transcodes running and not hit even 75% CPU usage, so I was surprised two transcodes was maxing it out with HandBrake and FFmpeg. I'm guessing I could make a plugin and limit the threads used via a paramater of the command, would that be correct?

One last thing, I haven't been able to find it online, but what is the general worker for? It appears to  list it's status as transcoding, so I'm unsure of the difference between the two workers.

Thanks again!

**Comment by HaveAGitGat** [comment]
It depends on the CPU and hardware bottlenecks. Some more powerful processors only hit 30-40% when running a single transcode so that's why it's necessary to be able to run multiple workers.

Plex server transcodes are throttled so that's why they don't max out your CPU. I don't think you can limit threads with HandBrake but you can with FFmpeg using the '-threads' flag.

If you hit the Workers info button it will tell you what they do ;):

![image](https://user-images.githubusercontent.com/43864057/72629813-f50e3900-3948-11ea-8d7a-e3e12a8878fb.png)

`General workers process both transcode and health check items. They prioritise health check`

Hope that helps.

**Comment by Viceman256** [comment]
That makes sense! You've been a great help, thank you for explaining to a novice like me :)

**Comment by HaveAGitGat** [comment]
No problem!
