### ISSUE TITLE
Add login/authentication

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#144]
**Is your feature request related to a problem?
Anyone on local network can use Tdarr

**Describe the solution you'd like**
Add authentication page

**Comment by Nonobis** [comment]
+1

**Comment by dualznz** [comment]
+1
As I would to be able to access this via my proxy server but opening it to the web at this stage is just too dangerous

**Comment by HaveAGitGat** [comment]
My main concern with this is that I'm no security expert so wouldn't feel confident implementing this on my own/without review. I've heard Organizr auth is a decent way to achieve this.

**Comment by alexandzors** [comment]
I'd let outside services handle this. 

e.g Reverse Proxies (Basic Auth, Tokens, LDAP, etc), organizr.

I don't see the need to have this exposed to the internet. If it's just for monitoring purposes it would be better to have a script that exposes metrics and have Prometheus/Grafana handle the outside (WAN) viewing. 

imo.

**Comment by HaveAGitGat** [comment]
After some more thought better to close this and let dedicated auth apps handle that side of things. 

Organizr:

-Installation
https://docs.organizr.app/books/installation/

-ServerAuth:
https://docs.organizr.app/books/setup-features/page/serverauth

-App examples:
https://github.com/organizrTools/Config-Collections-for-Nginx/tree/master/Apps

**Comment by marshalleq** [comment]
I was letting this one go cause I thought it was probably on a to do list somewhere,  but after the closing of it and reading @alexandzors comment, I am concerned that the intent of the request has been lost in translation, possibly due to assumptions.  One person commented that they wanted to access it over the internet, but that was just one person.  

To me it's just good practice to provide the option to lock down an app from a security standpoint.  Indeed, this is what the rest of the *arr apps allow you to do, and there are very good reasons for this.

Security issues don't just come in 'direct' over the internet like was suggested above, rather they come in via holes, get inside and then wreak havoc on anything not locked down from the inside.  

When you further consider (as in my case) that Tdarr may be running on a database shared with other apps e.g. nextcloud, Wordpress) it's not fun to think what one might do to the other.  

Organizr does nothing to address any of these issues.  My suggestion therefore is to put it on a long term roadmap somewhere, rather than just shut it down altogether.  I do expect it will be requested again.  I would certainly use it.

What you have achieved with Tdarr so far, is nothing short of astounding, so we gotta have some longer term goals too huh! :)

**Comment by alexandzors** [comment]
> Security issues don't just come in 'direct' over the internet like was suggested above, rather they come in via holes, get inside and then wreak havoc on anything not locked down from the inside.

Didn't think of that possibility as all of my stuff runs via docker on a VM on its own secured network. Then again I'm not your average Plex guy so. I agree having this on a long term road map would be great as it would be inline with the other "rr" apps.

**Comment by snickers2k** [comment]
"- New authentication system (can now log in with Discord if you have the 'Patreon: Supporter' role)"
was in changelog a year ago.

should this still being in pro version only? since the missing auth is the only reason i can't use tdarr; i don't really think it's really a "pro" feature? :/

please add to normal version .. one year is enough for pro members to have it upfront.

thanks

**Comment by supersnellehenk** [comment]
@snickers2k please don't resurrect old threads. But it's explained above https://github.com/HaveAGitGat/Tdarr/issues/144#issuecomment-591331703

There isn't any authentication for Tdarr. Just for the pro features, which does not include authentication for Tdarr itself.

**Comment by marshalleq** [comment]
I think there are two different conversations going on here:

1 - Authentication that prevents anyone gaining unauthorised access to tdarr
2 - Role based authentication that differentiates various groups of customers and associated features / capabilities

It seems like tdarr is not interested in #1, #2 already exists for those that pay for extra capability.

**Comment by SHoover80** [comment]
So in short they're just too lazy to script authentication or lack the skill expecting one to pay them to utilize Discords authentication process. Yea, i wont be using this software afterall. I consider network security a prioraty and clearly they dont care about security. Sure these people who use default wifi password and a single password for all their online account dont realize the risk, but I do.

**Comment by HaveAGitGat** [comment]
@SHoover80 thanks for checking out the issue, I think you’re misunderstanding the situation. Discord hasn’t been used for any sort of Tdarr Pro feature authentication in almost 3 years, you use https://tdarr.io for that to get a key.

In terms of local login authentication for security purposes, please check here as it’s what you’re after:

https://github.com/HaveAGitGat/Tdarr/issues/297

It’s still a pre-release but has been working well for me and haven’t received any issues with it. Have had a few different things going on this year but looking to fully release soon (not sure how it’s April already, time flies). Perhaps check it out if you’re a Docker container user and let me know if you have any issues on that other post. Hope that helps.

**Comment by SHoover80** [comment]
@HaveAGitGat Just basing on what I read above. I've searched the provided documentation and seen no information about enabling authentication, #297 you referenced and it gave information on how to add authentication when running in docker. But I'm running it on a Windows Server as it has my spare GPU. I've found no documentation reguarding setting up authentication. I do appreciate the quick response but reguarding setting up self hosted service, authentication shouldn't require extra research to setup. It should be enabled by default. Or at the very least direct one how to setup through the tutorial. Or simply profide info on how to setup through the documentation. True local services are less likely to get compramised But if another device on the same network gets compramised or guest get on your network who have a compramised device this leaves the device hosting this more vulnerable.

**Comment by HaveAGitGat** [comment]
2.18.01 released with auth: 
https://github.com/HaveAGitGat/Tdarr/issues/297

@snickers2k sorry that post references the dev docker images which are what are mostly used for trying new features. There wasn't any documentation aside from on that issue as the feature wasn't released yet. Added documentation here: 

https://docs.tdarr.io/docs/other/authentication

In terms of auto-enabling or doing it during setup, might add that in future.
