### ISSUE TITLE
Feature Request - Add Optional Output Directory

### ISSUE THREAD

**Issue by Torqu3Wr3nch** [HaveAGitGat/Tdarr#20]
I'd like to request a new feature- the ability to add an (optional) output directory, like in HBBatchBeast. Sometimes I don't know if the transcode is going to pan out and actually be an improvement on the source file. It would be nice to therefore not lose the source file pending manual review of the output.

It's also nice to know that anything in the completed folder is truly completed, so that you can go ahead and move those files. Currently, the folder at any point in time could be a mishmash of pending transcodes and completed transcodes.

**Comment by marshalleq** [comment]
Yes, I've actually had to set up a separate folder with a separate library and manually copy files into that, test them, check them etc then copy if I like them.  And the point is, so far I don't like any of them - still tweaking settings and am not yet convinced it's working as it's meant to.  That's expected for a pre-alpha product, but nevertheless we need a dev mode / test mode / digital twin mode or something cool like that.

**Comment by Torqu3Wr3nch** [comment]
I'm using Tdarr purely for conversions- I wouldn't dare plug one of my Plex libraries directly into a Tdarr library even with the "perfect" HB settings. For one, there's no such thing as a perfect, one-size-fits-all setting and second, there are some H264 files that will not benefit from a conversion to H265 (low-bit rate H264 files may actually get bigger with a "high quality" H265 conversion).

Therefore, ideally, we would be able to have an optional output folder (like we have in HBBatchBeast). A second nice feature would be to include a setting like HBBatchBeast has which compares the file size and only keeps the conversion if it's smaller.

**Comment by marshalleq** [comment]
Yes!  I didn't end up using HBBatch beast, but if it did some kind of comparitive logic, i.e you set a setting to say 'I want my files smaller' that would be soooo cool!  @HaveAGitGat could say it has Machine Learning and Artificial intelligence lol - though clearly that's a stretch.

Nevertheless, having an 'intent' switch to coax the logic would be quite the killer feature.  I really like thinking 'customer oriented' language with these things because it's very stylised to use case, which is what good products are all about.

E.g. Intent could equal -> Smallest Size, Highest Quality, Fastest Speed.
An environment type intent could also be added -> Post processing, Automation Processing, Health checks etc that could set up to match various environments.

You could even go so far as to query the hardware on the host and make some decisions based on that and how many days/weeks/years to encode the library - that would be fantastic information upon which to base decisions on.  E.g threadripper could do more HEVC encoding that core 2 duo, if you set intent to quality or speed and had a GPU that could come out with a GPU based recommendation.

**Comment by HaveAGitGat** [comment]
Haven't forgotten about this, just working on getting the initial project aims bug free.

**Comment by Torqu3Wr3nch** [comment]
Thanks, @HaveAGitGat. I appreciate the ping. I think a higher priority would be to have a setting to only override files where the converted file is smaller. I just had a directory wiped out where the conversion to HEVC ended up being significantly larger than the original source content!

**Comment by HaveAGitGat** [comment]
Added in 1.006. Will need some testing/feedback but seems to be working with normal transcode settings as well as when using multiple plugins. Need to decide what to do with completed files though - do we keep them in the Tdarr database or not (they're not techically in a Tdarr library anymore so should be removed, I've left them in for now so it's easy to see what has been transcoded on the transcode sussess tab).

@marshalleq  not sure about your second point. It seems to be a whole other request in itself. Seems a bit complex for now but maybe at a later date.

**Comment by forresthopkinsa** [comment]
Is this still an option in V2? Is this configuration documented anywhere?

**Comment by toxic0berliner** [comment]
Also looking for this to consider start. Any news on this?
