### ISSUE TITLE
Transcode success not showing in success tab

### ISSUE THREAD

**Issue by hdy2jsd3** [HaveAGitGat/Tdarr#203]
**Describe the bug**
Upon completion of a transcode the file does not move to the success tab. Instead it goes back into the queue with the new codec (HEVC in this case). 

**To Reproduce**
Encode a file. 

**Expected behavior**
Upon completion the file moves to the success tab. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mint 19.3 Docker 19.03.8
 - Browser Safari / Chrome
 - Version 1.108

**Additional context**
I know this was addressed in a previous thread and was supposed to be fixed but I’m still seeing it.

**Comment by HaveAGitGat** [comment]
Hi, this is expected behaviour. Newly transcoded files are put back into the queue and then pass through the plugin stack again to make sure all conditions are met.

The GitHub issue mentioned previously was referring to a bug where the file would be put back in the transcode queue twice after a single transcode due to the folder watcher rescanning the file several minutes later.

**Comment by marshalleq** [comment]
Just following along, is @hdy2jsd3 jumping the gun here (ie just needs to wait), or does a succeeded file never end up in the succeeded queue?

**Comment by hdy2jsd3** [comment]
False Alarm. As @HaveAGitGat stated, it does go back to the queue one more time. I just didn't wait long enough. Break. This software is amazing! Can't believe I've gotten along so far without it!

**Comment by HaveAGitGat** [comment]
Please you like it :)
