### ISSUE TITLE
Can't turn off health check for library 

### ISSUE THREAD

**Issue by OuticNZ** [HaveAGitGat/Tdarr#204]
**Describe the bug**
In a library with ISO files the health check will fail with ffprobe error when none of the options are selected.  I thought not having any of the health check options selected would mean that health checking should be disabled for that library.  But it appears not to be the case.  

When the health check fails it also puts the file into the transcode error/cancelled tab.  If I then manually retry the transcode it is processed correctly by the transcode plugins.  

**To Reproduce**
1. Create Library pointing to folder with ISO files
2. Set containers to "iso"
3. Under health checks unselect both options
4. Scan folder for files

**Expected behavior**
The folder should be scanned or any new files should be discovered but a health check should not be run.  

Version: 
Beta 1.108

**Comment by HaveAGitGat** [comment]
The health check isn't meant to be turned off. If you're not wanting to health check then don't start any General or Health Check workers. If a file comes through as health check failed which is actually fine, then there is the option to ignore that result.

Regarding the second issue, that is not how it works. If FFprobe fails to read a file, then it is placed in the Transcode: Error/Cancelled and Health check: Error/Cancelled tabs automatically as it is likely that HandBrake and FFmpeg will fail with the file. However, as you've mentioned, this is not always the case so I've changed things for 1.109 so that files will still be put in the Transcode queue if FFprobe fails to read the file.

**Comment by HaveAGitGat** [comment]
I’ll change it so that health check can be unselected for a library. Files will automatically be marked as ‘Ignored’.

**Comment by OuticNZ** [comment]
Thanks for the update.   Appreciate the work.

**Comment by HaveAGitGat** [comment]
Added for 1.109
