### ISSUE TITLE
Launch on System startup

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#207]
**Describe the bug**
I notice that you have removed the instructions on starting as a windows service. Can you please advise how i get tdarr to launch on startup. (Windows 10)

**Comment by HaveAGitGat** [comment]
Hi,  people were having issues with the 2 methods posted (due to bugs/incorrect configs in other projects) so I decided to remove them so there aren't any steps at the moment. To launch on start-up you could create a shortcut to a batch file and add it to your start-up programs or something along those lines.

**Comment by HaveAGitGat** [comment]
This will be dealt with under: https://github.com/HaveAGitGat/Tdarr/issues/207
