### ISSUE TITLE
Resolution matching

### ISSUE THREAD

**Issue by Xe138** [HaveAGitGat/Tdarr#22]
The resolution matching seems to require an exact match for vertical and horizontal pixels to identify as 480p, 720p, 1080p, etc.  Videos are often cropped down to a narrower aspect ratio (i.e removal of black bars) but should still be considered 480p, 720p, 1080p, etc.

Resolution should be determined by the horizontal pixel count only and should have a tolerance of a few pixels.  This should move most of the "other" resolutions into useful categories.

**Comment by HaveAGitGat** [comment]
There is a +-10% tolerance already for resolution so I think we’d need a different solution instead of increasing the tolerance further.

Using only horizontal pixel count could work but might give unexpected results for example if people are expecting a 1080p video to be around 1920*1080 and instead it’s 1920*300.

**Comment by Xe138** [comment]
After cropping, most 1080p movies are 1920x800.  Perhaps compare horizontal pixel count and an aspect ratio range (e.g. 1.5 - 2.5)?

**Comment by HaveAGitGat** [comment]
Tbh I think I'll just implement your original idea to increase the vertical range allowed for each resolution type. It will keep it simple and will work for 99% of use cases. My example of a 1920x300 would be extemely rare.

**Comment by HaveAGitGat** [comment]
Fixed in 1.005
