### ISSUE TITLE
Feature request: Drop down menu for plugin inputs.

### ISSUE THREAD

**Issue by awk-dk** [HaveAGitGat/Tdarr#221]
**Is your feature request related to a problem? Please describe.**
When setting f. ex. encoding presets it would be nice to have a list of presets to select from, instead of having to look up names to fill in manually in a text box.

**Describe the solution you'd like**
Make it possible to set up an array with name and description of possible values for an input, and return the index of the selected value in the array to the plugin.

**Describe alternatives you've considered**
You could put a list in the tooltip, but it could become very long, plus there is the risk of typing errors.

**Comment by Migz93** [comment]
This would actually be pretty nice. Really be handy to have people select from a drop down, especially when some variables are case sensitive, so if we forget to toLowerCase() it then it won't work as intended.

Not to mention the ease of use for the user just selecting what they want and it should take up less space on the plugin information because we won't need to put examples.

**Comment by HaveAGitGat** [comment]
This has been added to the July to-do on Discord.
