### ISSUE TITLE
"Oops! Something went wrong." when accessing the Libraries tab

### ISSUE THREAD

**Issue by jlasky** [HaveAGitGat/Tdarr#291]
This causes all of the other tabs to also show "Something went wrong" but will not show up until I click Libraries. I am running UnRAID and the most updated Tdarr repo.

This happened with the tdarr_aio repo, so I trashed it and pulled the tdarr repo. It worked for a while, essentially until the entire library was scanned, and now it is showing the same problem.

To reproduce, I pull the repo, scan my library files, and wait. After a bit of time, when I click "Libraries" then I am met with "Something went wrong" for every tab.

The logs show:

```

at checkScheduleChanged (server/main.js:2135:13)
at server/main.js:2159:29
at /app/Tdarr/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
[91m[2020-10-14T15:06:39.757] [ERROR] tdarr - [39mTypeError: Cannot read property '87' of undefined

```

**Comment by HaveAGitGat** [comment]
This error is to do with the libraries becoming 'undefined' in the database (i.e. corrupt). How have you mapped `/var/lib/mongodb` in the container settings? Are you using a folder or a Docker volume? Is there a process/service that might be interfering with writing to that location?

Someone mentioned this on the Discord but setting the libraries up again seems to have fixed the issue.

**Comment by jlasky** [comment]
I see - I believe that I have the TdarrDB mapped incorrectly in the docker settings.

The `tdarr_aio` repo has it automatically mapped to `/mnt/user/appdata/tdarr-db` and that had worked in the past for me. When I switched to the `tdarr` repo, I had the DB mapped to somewhere else.

I'll keep working on it and see if I can get it working again!

**Comment by Faitmaker** [comment]
I have the same problem with Beta 1.3004 on Windows 7.

```
[2020-10-17T09:14:07.886] [ERROR] tdarr - TypeError: Cannot read property '153' of undefined
    at checkScheduleChanged (server/main.js:2218:13)
    at server/main.js:2242:29
    at D:\Tdarr\bundle\programs\server\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:43:40
```

**Comment by sienar1** [comment]
I had this issue yesterday with 1.3003, with similar errors logged as @Faitmaker. I hit the Clear Database button on the Dev tab and then restored the most tdarr backup and it's been fine since.

**Comment by reloxx13** [comment]
had this 2 times on on win10x64

**Comment by reloxx13** [comment]
and again. not useable anymore

**Comment by Prolesious** [comment]
I've been having the issue as well.

**Comment by HaveAGitGat** [comment]
@reloxx13  @Prolesious sorry about that. I have been re-writing Tdarr for the last month or so, v2 is almost ready. You can see my update posts here.

https://www.patreon.com/posts/project-update-43016162

https://www.patreon.com/posts/v2-features-44647423

**Comment by alexholliz** [comment]
@HaveAGitGat is there a clean way to extract our plugin stacks from a backup? I've tried clearing the DB and restoring from backup to get around this issue as worked for some other folks, but that didn't work for me. 

My next goal is to just extract my plugin stack (and ffmpeg arguments) and make a new instance of tdarr with a smaller library, if that's possible.

**Comment by MRobi1** [comment]
Add me to the list of having this error. Restored from a backup a few days ago got me back into it.
Sounds like 2.0 will have the fix :)

**Comment by MRobi1** [comment]
This seems to now be a daily occurance. Just ran into it for the 3rd time in as many days.
I think I'm just going to shut tdarr down until v2 comes out.

**Comment by MRobi1** [comment]
I caved after posting yesterday and restored from backup for the 3rd time.
Just now... "Opps! Something went wrong."
So frustrating. Basically unusable for me. 4 times in 4 days. Hopefully 2.0 whenever it happens to be released will be more stable than this.

**Comment by MRobi1** [comment]
@reloxx13 I'm running on docker, but I never thought to check out the tags. I had just been using :latest which is 1.3003. Come to see there's been lots of updates since then and the v2 preview went up yesterday. Just pulled down the latest image and right away I'm not happy...
"chown: changing ownership of '/home/Tdarr/Media/TV/This Is Us/Season 05/This Is Us - S05E02 - Forty - Part Two.mkv': Invalid argument"
It is literally going through my entire library trying to run a chown command on every file. 
That could cause some serious permission issues in every other app!!
Maybe I'll just go back to unmanic and keep it basic and simple.

**Comment by reloxx13** [comment]
dont forget this is a peview, it could still be a bug and getting fixed. use it on a test library first

**Comment by HaveAGitGat** [comment]
Have not seen this error mentioned with this in v2 so it should now be fixed, sorry for the wait:

Documentation is here:
http://tdarr.io/docs/

**Comment by HaveAGitGat** [comment]
> @reloxx13 I'm running on docker, but I never thought to check out the tags. I had just been using :latest which is 1.3003. Come to see there's been lots of updates since then and the v2 preview went up yesterday. Just pulled down the v2 preview image and right away I'm not happy...
> "chown: changing ownership of '/home/Tdarr/Media/TV/This Is Us/Season 05/This Is Us - S05E02 - Forty - Part Two.mkv': Invalid argument"
> It is literally going through my entire library trying to run a chown command on every file.
> That could cause some serious permission issues in every other app!!
> Maybe I'll just go back to unmanic and keep it basic and simple.

You sorted that out right?

For anyone who has the same issue, the following folders are chowned on startup:

```
                /home/Tdarr
                /temp
                /logs
                /app
```

**Comment by HaveAGitGat** [comment]
> dont expect much, u can test the 2.0 urself already. https://github.com/HaveAGitGat/Tdarr/tree/master/updater
> 
> its horible overcomplicated developed. splitted into 3 applications and all 3 together almost reach **3gb** of file size.
> to have a comparsion, im a developer of a huge CRM web application and im not reaching 300mb in code.
> the dev just fucked up. instead of using a basic MVC like expressjs, i dunno what s*** he did to reach 1gb. sourcecodes are simple textfiles of some kb sizes.
> 
> setting up all 3 instances, (on windows) is a pain in the a**.
> 
> and all that for a simple converting page.
> 
> guess ill have to start my own application.
> 
> even when it may work now, the ui did not change much and those 3 apps will eat alot of power (energy).
> 
> ![grafik](https://user-images.githubusercontent.com/14855001/104519305-8619fd80-55f9-11eb-859d-d94d8ec10ad0.png)
> ![grafik](https://user-images.githubusercontent.com/14855001/104519454-bbbee680-55f9-11eb-954d-c38e902a3945.png)
> ![grafik](https://user-images.githubusercontent.com/14855001/104519507-d2653d80-55f9-11eb-8bc3-fc34d8e47a12.png)
> ![grafik](https://user-images.githubusercontent.com/14855001/104519575-f032a280-55f9-11eb-9d72-2c6548731cba.png)

Hi thanks for the feedback. If I was going for the smallest file sizes possible then I wouldn't be using this method. Tdarr comes with a lot of binaries included which increases the packaged file size. I would prefer it this way so it's 'one click run' instead of having to download lots of external dependencies manually. The binary sizes are large because they come with nodejs included. No need to install nodejs separately which is something new users struggle with if they have not used it before.

Sure, there are plans to have the WebUI and the Server in the same package soon. The Tdarr_Node still needs to be separate as that is something which is designed to be run independently, whether on the same machine as the server or another.

The size of all unpacked modules at the moment is about 2GB (note: previously downloaded packages are stored in the .staging folder so you don't need to redownload them if you want to change version.)

The 2GB size will be cut down a large amount within a week or so with some optimisations.

**Comment by HaveAGitGat** [comment]
Please reopen if you still have this issue on v2.
