### ISSUE TITLE
Transcoder leaves empty folders in transcode directory

### ISSUE THREAD

**Issue by Xe138** [HaveAGitGat/Tdarr#3]
After successful completion or an error on a transcode, the transcoder leaves empty folders.

Expected behavior: The transcoder should remove empty directories after transferring successfully transcoded files or on an error if the created directories remain empty.

**Comment by HaveAGitGat** [comment]
@Xe138 thanks for this suggestion.

The problem is, say there are 2 workers both writing data to the same folder:

Worker 1 ——> /output/test/1.mp4

Worker 2 ——> /output/test/2.mp4

If worker 1 finishes its file and tries to delete ‘test’ this may cause errors or stop worker 2.

Also consider this: 

Worker 1 is writing a file to ‘test’. Worker 2 is about to start writing a file to ‘test’. Worker 2 sees that there is a folder called ‘test’ so it does not need to create it. However, Worker 1 deletes ‘test’ just before Worker 2 starts using it, this causes an error and Worker 2 fails.

Perhaps it would be better to have a daily schedule to delete the files when no workers are running? For example every day at midnight?

**Comment by Xe138** [comment]
Right, the logic to make this work is probably more complicated than it's worth at this point.  My only concern is that it's difficult to tell what's happening in the directory, especially if there are any incomplete files being left behind.

A simple temporary solution might be a button to manually clear the transcode directory that only works if all workers are stopped.

**Comment by marshalleq** [comment]
I think it must do it for the health checks too, as I noticed an insane amount of empty directories in my cache folder and at that point had never attempted an encode.  I agree, there should be some what to clean it up.  I think most apps probably do it by using lock files and random directory names or file names within a single directory.

**Comment by marshalleq** [comment]
I'll add that if you look at my other post [here](https://github.com/HaveAGitGat/Tdarr/issues/10) that would cover the issue Xe138 has raised about understanding what is going on.  To that end, the cache directory could just be a bunch of hidden random named files with locks that are deleted with the completion / exit of each task.  I'm pretty sure that's what most apps do.

**Comment by HaveAGitGat** [comment]
Added in 1.003

Health check no longer creates folders.

Folders in caches which have not been modified in 24 hours (generous) are cleared.

**Comment by molly78** [comment]
A quick windows fix

save as .ps1

`

$directory = "C:\Path\To\Directory"

function Remove-EmptyFolders {
    param (
        [string]$path
    )

    # Retrieve all subdirectories within the current directory
    $subdirectories = Get-ChildItem -Path $path -Directory

    # Loop through each subdirectory
    foreach ($subdirectory in $subdirectories) {
        # Recursively call the function for each subdirectory
        Remove-EmptyFolders -path $subdirectory.FullName

        # Check if the current subdirectory is empty
        if ((Get-ChildItem -Path $subdirectory.FullName -Force | Measure-Object).Count -eq 0) {
            # Delete the empty subdirectory
            Remove-Item -Path $subdirectory.FullName -Force
        }
    }
}

# Call the function to remove empty folders
Remove-EmptyFolders -path $directory


`
