### ISSUE TITLE
Radarr/Sonarr may delete associated files (srt etc) when Tdarr creates a new file

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#30]
Seems to be a bug with Radarr/Sonarr, although need to investigate a bit further.

https://github.com/Sonarr/Sonarr/issues/756

https://github.com/Radarr/Radarr/issues/3209

**Comment by crypto-vault** [comment]
This could be fixed with Tdarr saving temporary output file with extension with .partial~ extension when copying it over to output folder so that Sonarr/Radarr would not think the temporary file is an upgrade. This would at least fix it for cases where destination container is same as original container. If destination container is different than original container then Sonarr/Radarr will always probably think it's an upgrade.

**Comment by HaveAGitGat** [comment]
@crypto-vault added for 1.107
https://github.com/HaveAGitGat/Tdarr/issues/172

Should prevent the issue as you say some of the time. Will have to wait for Sonarr/Radarr to fix the issue on their end. More info here:
https://github.com/Radarr/Radarr/issues/2547
