### ISSUE TITLE
To become a Patreon

### ISSUE THREAD

**Issue by wsegatto** [HaveAGitGat/Tdarr#317]
I will gladly become a Patreon of this project. I would like to be able to perform the following, which currently does not meet my main objectives (I'm have Debian Buster ARMv7 32bits and another ARMv8 64 bits):

**Is your feature request related to a problem? Please describe.**
a) Problem: local plugins don't work. They currently throw errors in library dependencies.
b) Problem: the direct customizable plugin for handbrake/ffmpeg "loop". It starts over when it finishes the transcode, with no logs. Eternal loop.
c) Problem: there are copying errors for external drivers (smb) (EDIT: this also happens for local folders) with no possibility to retry the copy operation. Error Message: `Copy failed: Error: Unknown system error -139412464: Unknown system error -139412464, copyfile '/home/pi/tmp/Transcode/DARK-TdarrCacheFile-7CKwlGW4b.mkv' -> '/home/pi/tmp/Output/DARK-TdarrCacheFile-meuGljGGn.mkv'`
d) Recommendation: it would be interesting to document/handle the start path of the WebGUI, Server and Node, i.e. if I run /Tdarr_Server/./Tdar_Server, the config/log/db folders are created in Tdar's parent folder e.g. /opt/config, /opt/logs, which is simply wrong.
e) Recommendation: there are too much "INFO" logs, which make everything else harder to find. A warning/error level log filter would be great.
f) Documentation/Request: Tdarr does not work in ARMv8 (64bits) and the documentation states it works for "ARMv7 64" which does not even exist. It would be nice to really have a ARMv8 64 bits version available. Right now the updater does not even start.

Thank you for this project and your efforts! Count on me for beta-testing.

Best regards!
Will

**Comment by HaveAGitGat** [comment]
Hi ,

a.
As of 1.99.13, in plugins you can set any external dependencies which are required:

```
  module.exports.dependencies = [
    'import-fresh',
  ]

```
A lot of the local plugins require import-fresh so I've set that to be installed automatically. I'll be updating community plugins so they automatically install external dependencies.

b. 
I have not encountered, perhaps it is to do with the above issue. Worth trying again on 1.99.14. Enable verbose logs on Logs tab and you should be able to see the plugin output and determine why it's not working.

c.
I'm not sure about this. Worth trying 1.99.14 as a lot has changed since 09.

d.
I will be posting the updated documentation tomorrow but everything is relative to Tdarr_Updater. Subfolders are created in the same folder from which it is run.

e. I can add this in at a later date.

f.
I build the arm packages on a Raspberry Pi which by default runs ARMv7 64.

**Comment by HaveAGitGat** [comment]
d should now be fixed:

https://github.com/HaveAGitGat/Tdarr/issues/326
