### ISSUE TITLE
Tdarr_Updater_Config.json doesn't always honor "false"

### ISSUE THREAD

**Issue by jasonsansone** [HaveAGitGat/Tdarr#325]
**Describe the bug**
Tdarr_Updater_Config.json allows a user to enable or disable modules.  If  `"enabled": false`, is set for a module it will not be downloaded during future runs of ./Tdarr_Updater.  However, the false flag is ignored if `currentVersion` is removed from the modules code.  The module will be re-downloaded.  The false flag should always be honored and version code skipped.

WORKS:
```
    "Tdarr_Desktop": {
      "enabled": false,
      "requiredVersion": "latest",
      "currentVersion": "2.00.00"
    },

```
DOSEN'T WORK:

```
    "Tdarr_Desktop": {
      "enabled": false,
    },
```

**To Reproduce**
Install v2 on linux.  Rerun ./Tdarr_Updater after modifying Tdarr_Updater_Config.json.

OS: Ubuntu 20.04.1 LTS as LXC container on Proxmox 5.4.78-2
Tdarr Version: 2.00.00

**Comment by HaveAGitGat** [comment]
This is due to the comma on the end which makes it invalid JSON: 
`  "enabled": false,`

Remove the comma and it should work. Please reopen if you still have that issue. The error will show in the terminal if the config is invalid:

`Error reading config file:SyntaxError: Unexpected token } in JSON at position 97`

**Comment by jasonsansone** [comment]
Confirmed.  I clearly need to study my json closer.  Sorry for the wasted time on the issue.  Thank you!
