### ISSUE TITLE
[Feature request] Health check before transcoded/changed file is moved into place

### ISSUE THREAD

**Issue by tyhawk** [HaveAGitGat/Tdarr#355]
Sometimes transcodes or other jobs don't go as they should and the output file is corrupted. Its health is checked after it is moved into place, but then it already replaced the original file with the corrupt version, forcing you to replace it again with the original file. I've set Tdarr health checks to "Thorough" to catch these files ASAP as I noticed the "Quick" health check can easily miss corruption as long as the headers are okay (seen this a number of times with version 1).

As version 2 already has a cache directory, it would be great if a health check would be performed on the output file. If the health check is okay, it will be copied into place by the server, otherwise marked as failed and either deleted or left in the cache dir. This should in theory prevent any corrupted files from slipping through and ending up in your libraries.

**Comment by FreelancerJay** [comment]
This would also help with libraries that send completed files to a different output directory, since at the moment the post-encode healthcheck always checks the file in the Library file, and doesn't seem aware that the new file is elsewhere

**Comment by dbensmith** [comment]
> This would also help with libraries that send completed files to a different output directory, since at the moment the post-encode healthcheck always checks the file in the Library file, and doesn't seem aware that the new file is elsewhere

Currently on 2.00.25 with a different output directory set and source file set to delete, the post-transcode health check takes place after the file is moved to the output directory, but not before Sonarr/Radarr pick up the file and rename/reorganize it, so the second health check always fails since the file was moved and renamed.

This feature would solve my problem as well as the problem of accidentally overwriting good files with broken files. +1

**Comment by HaveAGitGat** [comment]
Added a flow plugin for this:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/ecfcb2f5-f178-41be-8abb-388fef287aa8)
