### ISSUE TITLE
Unraid container permissions

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#36]
`but both of us have noted that the template continues to randomly add / change fields when you restart the container and that permissions inside the appdata config (the one mapped to /home/Tdarr/Documents in the container) are not being set correctly.  Roxedus discovered some things missing in the template, but the former issue has not yet had any action.`

May be cause of fresh scan on start.

**Comment by marshalleq** [comment]
I think that's my quote above right? ;)

Certainly the random changes to the docker template were happening prior to the scan on start feature being implemented - so I don't think it will be that.

**Comment by HaveAGitGat** [comment]
@marshalleq it is indeed. 

GilbN mentioned that templates reset to the default options every time you update the container in unRAID. Might be best to pull it from DockerHub and manually configure instead of using the template.

Permission issue should now be resolved in 1.004

**Comment by marshalleq** [comment]
Hey thanks for all your hard work.  I am loving Tdarr for the most part.  I'll monitor it and see if this issue persists (I haven't been taking any notice lately).  However, I'm struggling to accept the suggestion to go directly to dockerhub when the issue is only with this one unraid template (i.e. clearly not an unraid issue, more a how is this template created issue).  I do appreciate however that we may not yet have all the skills on board to help solve this now, and also that this ticket actually had two issues within it.  So how about if I see the template issue again, I'll open a new ticket, link to this one and describe it.  That way as tdarr becomes more popular maybe someone can help with this particular issue that is clearly unraid specific.  Or maybe I'll manage to learn enough about it to fix it myself.  I'm quite interested in this kind of thing.

Many thanks.

Marshalleq

**Comment by HaveAGitGat** [comment]
@marshalleq  ok I'll leave this open in case anyone encounters the issue. I was under the impression from GilbN that this happens with all containers on unRAID as he said that's what happens with Plex too.

**Comment by luigi311** [comment]
@HaveAGitGat I have never seen unraid templates being reset on updates not even on Plex. That would cause issues with templates that rely on manual inputs and would be breaking all the time. That being said I don't think my unraid template reset itself when I last updated tdarr.

**Comment by marshalleq** [comment]
Hey I haven't seen this happen across the last few updates, so probably good to close.  Unless someone else wants to chime in.

**Comment by HaveAGitGat** [comment]
Yeah, no more reports. Closing.
