### ISSUE TITLE
Feature Request: Temporarily pause all workers within, and across all nodes

### ISSUE THREAD

**Issue by Tiwing1** [HaveAGitGat/Tdarr#434]
**Is your feature request related to a problem? Please describe.**
This isn't an existing problem. I have a distributed system with 5 nodes all transcoding a large library. However, I need to temporarily stop processing across all nodes so that I can manually move some large files between different disks. 

**Describe the solution you'd like**
All nodes are currently scheduled. Rather than having to go into each node separately and set all schedules to allow 0 transcodes and health checks, a "master pause" either at the node level or globally (or both?) would be an excellent addition. the node level pause would be good since it would allow individual nodes to be overridden from the server page. Global pause would be good to stop all processing if, for some reason a server restart is required. "Pause" would allow all workers to finish their tasks.

**Describe alternatives you've considered**
It is possible to do this today by going into each node and setting schedules to 0. However, it's cumbersome and with more than a couple of nodes remembering the schedule settings is difficult.

**Additional context**
none

**Comment by douginoz** [comment]
I have a related request.  I need to be able to tell tdarr to stop using a node temporarily.  I currently have a node schedule set up for that node as well as a library schedule for all nodes (set to run 24x7).  Because there is a node schedule, I can't simply change the Transcode GPU value to 0 (in the main page 'Nodes' window below 'Options').  When I do, tdarr simply changes the value back to 1 (it's clearly polling the Node Schedule every 10 seconds or so and ignores my attempt to override).

I think a simple solution would be to include a button in this section of the web page that lets me turn on or off the node - effectively overriding any schedules at any level.  When I toggle this to "Off", no further processing happens on this node (current processing continues until complete of course).  When I toggle this back to "On", normal scheduling resumes.

**Comment by HaveAGitGat** [comment]
Added a global pause in .17 which will pause the transcode, healthcheck queues as well as errored items in the staging section queued for 'Retry'. 

![image](https://user-images.githubusercontent.com/43864057/163718901-00b6cd7d-0602-4238-bbce-6ba41b25f5df.png)


Notification also displays on the other sections just so it's extra clear:
![image](https://user-images.githubusercontent.com/43864057/163718908-2ae86503-5a6d-4757-86f9-6798f8d204ba.png)


Also added a node pause option:

![image](https://user-images.githubusercontent.com/43864057/163718689-1daaebb7-160a-4752-a361-6595d95dffaf.png)
