### ISSUE TITLE
Ability to move the TDarr server between different operating systems

### ISSUE THREAD

**Issue by McKaiz** [HaveAGitGat/Tdarr#448]
First of all, thank you very much for this impressive project!

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
When re-importing a backup it would be cool to have the ability edit the data like the paths for the media folders etc. I have a TDarr server on a Windows Desktop (native) and would like to import it into a Docker container. The folder structure is the same although instead of a drive letter (Z:/aLibraryFolder) it would be absolut path (/media/aLibraryFolder).

**Describe alternatives you've considered**
Maybe instead of import functionality a tool to edit the backup zip? I tried to change the paths by and but it keeps crashing when import it to the docker container
**Additional context**
I have the TDarr server normally running on a Synology server as a Docker container. To improve the indexing I removed the Synology container and created a native Server on a Windows machine. After some time running, I wanted to move server configuration back to the Synology so that the Windows does need to run 24/7

**Comment by HaveAGitGat** [comment]
Hello, Docker volume mapping is designed for this. For example on Windows you can use:

`-v C:\Transcode\server/:/app/server`

If moving to Linux you can then use something like:

`-v /mnt/media/server:/app/server`

**Comment by ampersandru** [comment]
> Hello, Docker volume mapping is designed for this. For example on Windows you can use:
> 
> `-v C:\Transcode\server/:/app/server`
> 
> If moving to Linux you can then use something like:
> 
> `-v /mnt/media/server:/app/server`

I don't think this solves the file locations of all the files processed on a windows server

For example, in Windows, the file is mapped to
D:/TV Shows/XYZ/XYZ.mkv, this also is in the files within the fileJSONDB folder:
`{"_id":"Z:/TV Shows/XYZ/Season 02/02x04 - XYZ.mkv","file":"Z:/TV Shows/XYZ/Season 02/02x04 - XYZ.mkv","DB"`

When you try restoring a backup on a linux-based system, none of these files will be mapped and tdarr will want to re-process all files again since it believes everything are new files since folder structure is likely /volume 1/TV Shows/XYZ/XYZ.mkv instead

If there was a tool to convert all paths for libraries/files upon restoration of backup, that would be amazing

Someone had tried migrating from windows to linux:
https://www.reddit.com/r/Tdarr/comments/zufjja/tdarr_move_server_from_windows_to_linux_arm/

> The pathing is incorrect in the previously scanned files. Problems happen due to this.
> 
> This is not a workable solution.

**Comment by burfot** [comment]
I have the same use story. "I have a TDarr server on a Windows Desktop (native) and would like to import it into a Docker container."

Same issue.
