### ISSUE TITLE
Very slow copy

### ISSUE THREAD

**Issue by nathanbent** [HaveAGitGat/Tdarr#544]
**Describe the bug**
After completed transcoding the copy/move speed is very slow, or the server is not recognizing that it is able to perform the next copy/move.  There are many files awaiting copy/move.  I have the transcoding cache on the same drive pool as the media library, and it should be very quick if it can move the file.  There is no network activity, so it does appear that it is the server not recognizing that it can copy/move
**To Reproduce**
Transcode video succesfully
**Expected behavior**
Because the completed transcode is on the same drive it should be fairly quick if it can move the file, then healthcheck and delete the original and rename.
**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
Server config
{  
"serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": ""
}
- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
Nothing related to copy/move that I can find
-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
No worker errors
 - OS: Ubuntu 20.04, I've tried running both as Docker and as native application
 - Browser Chrome
 - Version 2.00.13

**Additional context**
Please let me know what else I can provide to help!

**Comment by HaveAGitGat** [comment]
Haven't had any other reports of this so wondering what might be causing it on your setup.

Tdarr uses mvdir and falls back to ncp.

https://www.npmjs.com/package/mvdir
https://www.npmjs.com/package/ncp

Not sure if you're familiar with NodeJS, if you are then perhaps try the above modules to see which one has an issue on your setup.

**Comment by HaveAGitGat** [comment]
Reopen if still having the issue on .14, thanks.

**Comment by Lucqqq** [comment]
I just had the same issue. Turns out it was a misconfigured plugin.
The "Keep original file dates and times after transcoding" plugin e.g. connects to the server via API.
This wasn't setup correctly which meant it would wait for a time out for every copy.
So check your plugins and transcoding options whether you have a similar situation.

**Comment by xeviff** [comment]
hello, I have the same issue. After leaving the computer working all the night I have like 90 transcoded files where 75 are still in "awaitingCopy" state. I have to say that the content is remote in a LAN server. 
I observed the network stats and discovered the following: when Tdarr were still converting, the speed was aprox. 60Mbps downloading and 20Mbps uploading which means the conversion task was taking more priority in terms of network, leaving the copy (uploading to server) with less priority and low speed.
I stopped conversion tasks and see what happen. The result was downloading got 0 and uploading increased to 60Mbps
![image](https://github.com/HaveAGitGat/Tdarr/assets/73612508/816fcc83-5ee8-42d4-8d17-dc51fc03c67d)

Now the copy seems to be faster, of course in the limits of my setup (server disk writting speed, network speed limits, etc). I guess the issue is normal, caused by a remote setup and I/O behaviour

**Comment by zedeska** [comment]
I have the same issue, copying file is very slow. I saw in task manager that the tdarr server process doesn't go above 1Mo/s disk usage, is it an intended cap? can you disable it somewhere ? I am copying from SSD to a network drive, but normally I get much better speeds.
