### ISSUE TITLE
Tdarr suddenly forgets all process and library files

### ISSUE THREAD

**Issue by Carl-Wilhelm** [HaveAGitGat/Tdarr#558]
Three times now, Tdarr has suddenly, without any input "forgot" the whole library. It will still transcode new files that are added to the folders, but the transcode queue is gone, Transcode Success is gone etc. It seems like it forgets all the files. I then have to go back to Librarys and do a "Scan Fresh" on the library, and then do a new health check on all files.

My library is close to 20 000 video files with only H264 and HEVC files.

I am running Tdarr on Windows 2016 Server, not in docker.
All disks are local on the machine.
No reboots.

I have attached the "log" from Tdarr_server from when it happened.

![image](https://user-images.githubusercontent.com/75078972/152858548-38976804-e06f-4807-89bb-c3e40e13ea63.png)

**Comment by HaveAGitGat** [comment]
All sorts of permissions issues are happening most likely because you've put Tdarr in `C:\Program Files` which is not meant for stored application data and often requires elevated permissions. Put Tdarr in an area where elevated permissions aren't required (such as in the user folders) and it should work fine.

Re-open if needed.

**Comment by Carl-Wilhelm** [comment]
Hi again.

I have moved Tdarr to a user directory. That did not help.
I also tried running CMD as administrator before running Tdarr. It looked like that helped, but after a couple of days, it was suddenly empty and all is forgotten.

Is there any tests, logs etc that i can run/check that can help find the cause of this problem?
