### ISSUE TITLE
Fantastic!

### ISSUE THREAD

**Issue by marshalleq** [HaveAGitGat/Tdarr#6]
I am very excited about this new tool.  Some things I've noticed:

- I've installed the docker and note there's not yet a how to get it started (once installed).  Not surprising at this stage, but probably would have helped me with some of the below.
- It's started with no libraries - even though it's mapped to standard locations in docker - I assume this allows sub libraries within the main mount point, however it also asks me for a transcode cache folder, even though one was set up to a default mount point in the docker.  Being a default mount point, shouldn't it default to that internal docker path?  e.g. /home/Tdarr/cache

- I add the source folder under /home/Tdarr/Media and it sees all the content under this via the docker mapping - however I have not way of adding the library and it still says 'No Libraries' up at the top left of the window.  I've tried clicking both scan buttons and nothing changes.
- Also being in docker on linux, it is slightly odd to see windows based formatting - C:/MySourceFolder showing up - something cosmetic to change for later maybe
- Clearly the first place to start is to get some stats active which I can't do due to the above.

What am I missing?  Happy to write it up in the Wiki for you once we solve it.

What does the worker sliders do?  I seem to be able to move them up to 1 without anything actually working.

Hmm, just tried scan again and it looks like it's working now by doing that.  Hopefully this helps someone else.  Once I figure it all out I'll add to wiki.  Thanks so much for making this!

**Comment by HaveAGitGat** [comment]
@marshalleq 

Glad you're interested in trying it! 

`I've installed the docker and note there's not yet a how to get it started (once installed). Not surprising at this stage, but probably would have helped me with some of the below.`

Have you used Docker much before? There is a bit of a learning curve but yes I'll be sure to include more detailed steps in future for people who have not used it. Even though you have mapped the libraries correctly in the Docker run command, you still need to add the libraries in Tdarr (using the internal container path which you mapped to your host PC). 

For example, you map the following path in the Docker run command:

>  -v /MyMedia:/home/Tdarr/Documents/Tdarr \

So the path 'home/Tdarr/Documents/Tdarr' inside the Docker container will point to '/MyMedia' on your host PC. When using Tdarr, you then need to add a library and put '/home/Tdarr/Documents/Tdarr' in the source folder and scan for files 'Scan (Fresh)'. All the files in '/MyMedia' will be scanned.

You then need to repeat the mapping process with the transcode cache folder.

> it still says 'No Libraries' up at the top left of the window. I've tried clicking both scan buttons and nothing changes.

I'm not sure what you mean by this. The scan buttons only appear once you have added a library. Are you able to post a screenshot?

>Also being in docker on linux, it is slightly odd to see windows based formatting - C:/MySourceFolder showing up - something cosmetic to change for later maybe

Yes sorry, that's because I do development on a Window's PC so put it there for now but will update it soon.

>What does the worker sliders do? I seem to be able to move them up to 1 without anything actually working.

The sliders launch and maintain the number of workers specified. Are you able to see items in the queues? If there are items then the workers will process them.

>Hmm, just tried scan again and it looks like it's working now by doing that. Hopefully this helps someone else. Once I figure it all out I'll add to wiki. Thanks so much for making this!

Let me know if you need any more help! A lot of information to take in.

**Comment by marshalleq** [comment]
Thanks very much - yeah I've got heaps of dockers, have run them on a few distros and currently using unraid.  Now that I've found you're on discord I'll move the conversation there, thanks!

**Comment by HaveAGitGat** [comment]
Seems resolved :)
