### ISSUE TITLE
Docker Synology library / n00b

### ISSUE THREAD

**Issue by 0brunoreis** [HaveAGitGat/Tdarr#620]
Hello everyone, I have trying to setup Tdarr but it seems I have it a wall. Tdarr Server doesn't seem to be able to find my library. My library resides in volume 1/video/movies. // TV-Shows - I have tried to connected with /media or /library with the same result. I have checked the user permissions but didn't find anything odd.

Does anyone have an idea or a clue that might help? any Synology user who was able to install it with docker? If everything works I'll add other nodes of course.

Thank you in advance for any help you might provide

**Comment by adefaria** [comment]
I will include two scripts I use for setting up Docker containers for servers and nodes. Here's my setup - I have a Synology 1019+ (Jupiter). I also have a Linux desktop (Earth) and a MacBook Pro running Ubuntu (Mars). Since Jupiter is my current Plex server I did not want to task with both running tdarr_server and a tdarr_node. So I set it up to only be the tdarr_server. It has the ability to do hardware transcoding but I left that for Plex to use when servicing my friends.

Earth is a honking desktop with an Nvidia GeForce card and I definitely wanted to utilize those GPUs. Mars doesn't have an Nvidia card and I posted an issue about how to best utilize it's GPUs right here under issues.

So the tdarr_server is set up by running the following on the Synology itself (I use ssh to log into Jupiter). You will need to adjust some parameters for your environment:

```
#!/bin/bash
mediaFolder=/Videos

# Stop any running containers
docker stop tdarr_server > /dev/null 2>&1

# Remove any old docker container
docker container rm -f tdarr_server > /dev/null 2>&1

# Recreate new docker container
docker run -d \
  -v $mediaFolder:/input \
  -v /System/tmp/tdarr_cache/:/temp \
  -v /System/Config/tdarr/:/app/server \
  -v /System/Config/tdarr/:/app/configs \
  -v /System/Config/tdarr/:/app/logs \
  -e "serverIP=0.0.0.0" \
  -e "webUIPort=8265" \
  -e "serverPort=8266" \
  -e "TZ=America/Los_Angeles" \
  --network="bridge" \
  -p 8265:8265 \
  -p 8266:8266 \
  -e PUID=1000 \
  -e PGID=1000 \
  --log-opt max-size=10m \
  --log-opt max-file=5 \
  --name tdarr_server \
  haveagitgat/tdarr

# With the container created start tdarr_server
docker start tdarr_server

# This is needed to set the restart option
docker update --restart=unless-stopped tdarr_server
```
I would highly recommend setting mediaFolder to some small subset of your library to test things before setting it loose on your whole media library. So make a /volume1/video/movies/test folder and set mediaFolder to that. Then, when you have both your tdarr_server and tdarr_nodes ready, simply copy some videos into /volume1/movies/test. tdarr_server should see them and farm out the work to your tdarr_nodes. The nodes will transcode the videos to the cache folder you configured and when completed, move them back to /volume1/video/movies/test when completed. If you like what they compressed to you could move them back in place under /volume1/video/movies. Important note - tdarr may take a Movie.avi and convert it to a Movie.mkv or something like that. If that's the case you can remove the .avi and replace it with the .mkv. Plex should pick up the change.

When you are satisfied that the transcoding works, change your mediaFolder to /volume1/video/movies and redo the Docker container for server and nodes.

Within tdarr, you set up libraries and there you define where this library resides and where the cache directory that tdarr does its work in resides. In my example above I map the $mediaFolder to /input and the cache dir /System/tmp/tdarr_cache to /temp. This means if you go into the Docker container using `docker exec -it tdarr_server bash` and do `ls /input` you'll see all your movies (or all your movies in your little test subfolder while testing). If you got that then the tdarr_server is seeing your data. Now you need to go into tdarr's web interface under Library and add a library with /input as the source and /temp as the cache. Then you can copy a video into /volume1/video/movie/test and watch it transcode via the web interface. Note you will have to have your tdarr_server running and at least 1 tdarr_node set up. Make note of the sizes of your test videos and compare them to the processed videos. They should be smaller and they may be converted from say a .mp4 -> .mkv.

As for me, under /Videos, I have Movies, Series, Concerts, Comedy, etc. So I made separate libraries for each and utilized the schedule to have different libraries be processed at different times.

**Script notes**:

1. mediaFolder is mapped to /input; /System/tmp/tdarr_cache is mapped to /temp
2. I map /app/server, /app/configs and /app/logs to /System/Config/tdarr. /System is a folder I mount to my Linux boxes so I can easily inspect the logs or config, for example.
3. Most of the rest of the settings are pretty standard. Feel free to ask questions.

```
#!/bin/bash

serverIP=192.168.0.251
nodeIP=$(ip address | grep 192.168 | cut -c10-22)
host=$(hostname)
mediaFolder=/Videos

# This just creates a pretty name for host with the first letter capitalized
Host=$(echo ${host:0:1} | tr [:lower:] [:upper:])$(echo ${host:1}   | tr [:upper:] [:lower:])

# Stop any running container
docker stop tdarr_node > /dev/null 2>&1

# Remove any old tdarr_node container
docker container rm -f tdarr_node > /dev/null 2>&1

# Create docker container
# This version does not add the NVIDIA stuff. I had a problem trying to
# create a docker container with Nvidia support for Mars but not for Earth.
# Seems the MacBook is not "CUDA cabable" but rather simulates CUDA using
# the CPU. This makes it very slow. It also makes it so we cannot specify
# Nvidia stuff here.
if [ "$host" = "mars" ]; then
  echo "Running docker container for Mars with no Nvidia support"
  docker run -d \
    -v $mediaFolder:/input\
    -v /System/tmp/tdarr_cache/:/temp \
    -v /System/Config/tdarr:/app/server \
    -v /System/Config/tdarr/$host:/app/configs \
    -v /System/Config/tdarr/$host:/app/logs \
    -e "nodeID=$Host" \
    -e "serverIP=$serverIP" \
    -e "serverPort=8266" \
    -p 8268:8268 \
    -e "TZ=America/Los_Angeles" \
    -e PUID=1000 \
    -e PGID=1000 \
    --network bridge \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    --name tdarr_node \
    ghcr.io/haveagitgat/tdarr_node
else
  echo "Running docker container for Earth with Nvidia support"
  docker run -d \
    -v $mediaFolder:/input\
    -v /System/tmp/tdarr_cache/:/temp \
    -v /System/Config/tdarr:/app/server \
    -v /System/Config/tdarr/$host:/app/configs \
    -v /System/Config/tdarr/$host:/app/logs \
    -e "nodeID=$Host" \
    -e "nodeIP=$nodeIP" \
    -e "nodePort=8268" \
    -e "serverIP=$serverIP" \
    -e "serverPort=8266" \
    -e "TZ=America/Los_Angeles" \
    -e PUID=1000 \
    -e PGID=1000 \
    -e "NVIDIA_DRIVER_CAPABILITIES=all" \
    -e "NVIDIA_VISIBLE_DEVICES=all" \
    -p 8268:8268 \
    --device=/dev/dri:/dev/dri \
    --network bridge \
    --gpus=all \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    --name tdarr_node \
    --runtime=nvidia \
    ghcr.io/haveagitgat/tdarr_node
  fi

# With the container created start tdarr_node
echo "Starting tdarr_node"
docker start tdarr_node

# This is needed to set the restart option
echo "Updating restart"
docker update --restart=unless-stopped tdarr_node
```
Here I have some code to differentiate between my desktop (Earth) and my laptop (Mars) since Earth can do hardware transcoding with the Nvidia GeForce and Mars cannot (yet). Again I map Docker volumes to mediaFolder and /temp as before. Note that I separate the configs and logs to different folders using $host so that the two different nodes are not overwriting the same config/log. Finally, there are some additional parameters to the `docker run` command for Earth in order for the Nvidia hardware transcoding to work - NVIDIA_DRIVER_CAPABILITIES, NVIDIA_VISIBLE_DEVICES, --device=, --gpus=all --runtime nvidia.

I also had to install some stuff on my Ubuntu desktop to get the necessary support for the Nvidia runtime to work in the Docker container as well as downloaded and compiled nvtop from source. nvtop allows you to see if your GPUs are being utilized. It was a pain but hardware transcoding is like 10 times quicker than CPU-only transcoding.

**Comment by 0brunoreis** [comment]
thank you very much, I'll try and do that tomorrow. what I don't get is why I was able to install Jellyfin, and whole bunch of container without any hiccup and now Synology is not letting me mount the drives. I can "log" into the server and I can even see the node. when I refreshed my library it just stays empty.

just in case I am missing something could you take a look, it would avoid me the long road.
https://imgur.com/a/KANQ1Sg

I have watched the most common videos on YouTube to see if I missed something or if I could extrapolate information to no avail.

Thank you advance once again

**Comment by adefaria** [comment]
I do see you have one tdarr node set up, hasty-hind. I think you also have a tdarr server named tdar_server. Is hasty_hind and tdar_server running on the same Synology?

Assuming you have ssh access to your Synology I would do the following:

1. ssh into your Synology
2. Run `docker exec -it tdarr_server bash`. This should give you a shell into the running tdarr_server docker container.
3. ls /media

If you see all your media then we know that the tdarr_server can see your media. Repeat this for your tdarr node (hasty-hind). Does the node also see the /media folder with all your movies?

One thing that seems missing if you have no cache mount. Create a folder say under /volume1/tdarr_cache. This folder must also be seeable from both the tdarr_server and any tdarr nodes. So add volume for video/tdarr_cache to say /temp (or it could be /tdarr_cache or /cache, whatever). Make sure this folder is also visible from both the tdarr_server and any tdarr nodes. Tdarr will take a video from /media and transcode it into /temp and only when completed will it move it back to /media replacing the bigger file with the more compressed one.

But this is not all! I think here is why you're not seeing the connection. In the tdarr WebUI click on Libraries along the top bar. Here you define a library. Read my previous post about making a test library and how to manage libraries. Basically, you click on `Library +`, name your library then fill out the `Source` and `Transcode cache` options. In our example that would be /media and /temp.

Here's a sample of one of mine:

![2022-05-09@14:42:10](https://user-images.githubusercontent.com/2692127/167503751-ace4b99d-f5ce-431a-b1bf-c78397a4270f.png)

![2022-05-09@14:42:27](https://user-images.githubusercontent.com/2692127/167503784-7a2af16a-836d-43fe-8a3e-ea98c9862a23.png)

![2022-05-09@14:43:53](https://user-images.githubusercontent.com/2692127/167503796-e5b75649-6dda-4c0d-b953-479472387bae.png)

Once you `Scan new` or `Scan fresh` Tdarr will scan the Source folder (which in our case is the /media folder in the Docker container which is connected to your video/Movies directory on the Synology) to queue up videos to be transcoded. It will also use the /temp folder in the Docker container (which is connected to your video/tdarr_cache directory on the Synology) as a staging area for transcoded files. Without a properly defined library, Tdarr does not know what to work on. It senses your tdarr node, but doesn't see any work to be performed.

**Comment by 0brunoreis** [comment]
Well... After ssh into my synology I was shown an error saying it couldn't see the library. Being extremely motivated I just decided to redo the installation, now I can't see neither, the node or library.

Can I used your instructions (the first time you answered) to install tdarr server and tdarr node via SSH? Would the same instruction work on a Ubuntu mate installation for a second node?

Thank you in advance,

**Comment by adefaria** [comment]
First, after you ssh into the Synology you should be at a shell right? So I don't understand what you mean when you say "I was shown an error saying it couldn't see the library". Who shown you that error? Who was "it"? 

I'm assuming you intend to run a Docker container of tdarr to serve as your tdarr_server and intend to use other machines to operate as clients. As such in order to get into the Docker container to "see what it sees" you would need to first ssh into your Synology and **then** `docker exec -it tdarr_server bash`. That's because the Docker container is running on the Synology. As for a tdarr_node running on my desktop (Earth), I'd just create and run the tdarr_node container on Earth and would get inside it by doing `docker exec -it tdarr_node bash` while on Earth.

Yes, you can use my scripts. The idea is to log into the Synology and run the script `tdarr_server` to set up and run the Docker container on the Synology machine. Then on a different machine running Linux, run `tdarr_node` (You may need to install docker first on the Linux machine). Again there will need to be some tweaks to the scripts. For example, the various `-v` (volume) options to `docker run` will need to be changed to where you put things in your filesystems. And my `$serverIP` is the IP address of my Synology on the LAN (I use 192.168.0.251 - yours is probably different)

**Comment by HaveAGitGat** [comment]
Reopen if needed, perhaps jump in the Discord instead. https://discord.com/invite/GF8X8cq

**Comment by 0brunoreis** [comment]
hello again, what I meant by "I was shown an error saying it couldn't see the library" is this message in the next image.
![Screenshot 2022-05-16 at 20 51 49](https://user-images.githubusercontent.com/98478473/168662358-665649ec-f5c0-45a2-a939-5b538358fb45.jpg)

**Comment by HaveAGitGat** [comment]
https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket


https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue

**Comment by 0brunoreis** [comment]
thank you,

**Comment by adefaria** [comment]
@0brunoreis I think it's better to add your username (BrunoReis) to the docker group. The second link describes how to do that.

Secondly, the 2nd parameter to docker exec (Tdarr) is the name of the container. In your screenshot that was tdarr_server *not* Tdarr. You can see the names of the containers in DSM's Docker GUI or just doing `docker container ls`. The other container was named "hasty_hind". The screenshot you did showing the WebUI showed one node named hasty_hind. You can name them what you want either in the DSM Docker GUI or from the `docker run` command it's the `--name <name>` parameter.

So then, when you get your Docker permissions thing worked out you should be able to `docker exec -it tdarr_server bash` and check your /media directory to see if the server sees your /volume1/video/Movies files mounted to /media. Then stop your tdarr_server container and go into it from DSM's Docker GUI adding another folder for the cache directory. So make a folder say /volume1/tdarr_cache and add the volume mount with tdarr_cache for the "File/Folder" column and say "/tdarr_cache" for the "Mount Path". Basically, the "File/Folder" column is what you see on the Synology (through say the ssh session or File Station or whatever) and the "Month Path" is how it's referred to *inside* the container. You can check this with:
```
BrunoReis@StorageB:~$ mkdir /volume1/tdarr_cache
BrunoReis@StorageB:~$ touch /volume1/tdarr_cache/file
BrunoReis@StorageB:~$ docker exec -it tdarr_server ls /tdarr_cache
file
BrunoReis@StorageB:~$ 
```
Here we created the tdarr_cache folder under /volume1 then created a file named "file" in that folder using the touch command. Then we used docker exec to execute the ls /cache folder and verified that "file" exists in the /tdarr_cache folder *inside* the docker container tdarr_server running on your Synology.

As for hasty_hind, I'm not sure where that docker container is running. If also on the Synology then stop the container in DMS's Docker GUI and make sure the volume mounts are the same as for tdarr_server. Then use the same commands above changing tdarr_server to hasty_hind.

If hasty_hind is running on another machine, say a Linux desktop, then do the Docker commands on that machine. Note however that I believe that both /media and /tdarr_cache in the container must refer to the same filesystem. In my set up these folders are accessible using NFS. You can use NFS too or perhaps something else like SMB (though SMB seems to be way slower than NFS).

Once both tdarr_server and tdarr_node (Known as hasty_hind in your setup) have access to your /media and /tdarr_cache, go into the WebUI and configure a library using those paths. Finally, add a few CPU/GPUs to get the process transcoding.

**Comment by 0brunoreis** [comment]
so everything went wrong and I just started all over, the good news is that my Synology has the Tdarr Server and a Tdarr node running. on that side now everything is fine (besides how slow running a node on the Synology is). I have a small gigabyte prix with ubuntu mate running on it. I installed docker, and cockpit (GUI for docker). Somehow (after looking all over the internet) i managed to install a second Tdarr node, but after loading and test library I get the error you see below.
this is the log from Tdarr:
![Screenshot 2022-05-17 at 20 34 57](https://user-images.githubusercontent.com/98478473/168886315-fb538dda-68ce-497f-bfe3-157149136eb4.jpg)

and the options menu is like this:
![Screenshot 2022-05-17 at 20 35 21](https://user-images.githubusercontent.com/98478473/168886500-deaa8af9-7407-4b48-99cc-009ce7b9e729.jpg)

I SSH into that docker container using docker exec -it hopeful_bell bash then ls /media but the folder showed empty, clearly it is not because the log file saw something...

these are the parameters of the docker container in my gigabyte brix:
![Screenshot 2022-05-17 at 20 44 14](https://user-images.githubusercontent.com/98478473/168887454-c987d154-94c7-4068-9b9e-5b55b6e542e2.jpg)

I think that I probably mounted incorrectly the share (on my Synology), any easy command I can follow?

After all this, when I am able to make everything run properly,  I'll install another node on a hp prodesk I have that has an i7. The prodesk is running Proxmox with only one VM. I am currently watching an YouTube video from techno tim because the ubuntu mate VM running on Proxmox doesn't get assigned and IP automatically.

thanks for all the help, you are providing. I hope this thread will be useful to others as well.

**Comment by 0brunoreis** [comment]
Just added more files, the node seems to come alive, see below:

![Screenshot 2022-05-17 at 21 21 24](https://user-images.githubusercontent.com/98478473/168893773-f90e94c3-66f0-4bea-add3-2c889d483685.jpg)
 
and then, 5 seconds later: 

![Screenshot 2022-05-17 at 21 22 05](https://user-images.githubusercontent.com/98478473/168893858-bb450af1-089b-4980-80cd-ef2dc39b4883.jpg)

![Screenshot 2022-05-17 at 21 22 18](https://user-images.githubusercontent.com/98478473/168893881-aae46d7d-69d4-4e81-a62a-92022b55fd86.jpg)

...

**Comment by adefaria** [comment]
You're making progress. You said you did a `docker exec -it hopeful_bell bash` and then an `ls /media` but saw nothing. I assume you did this on that gigabyte prix thing. The volume mount maps /media:/home/bruno/Videos. Two things. First, that seems to be backward. It should be <path to files on the host running docker>:<path inside the docker container>. So then that would be /home/bruno/Videos:/media.

Secondly, you had initially stated that the videos you wish to transcode exist on the Synology under /volume1/video/movies. Let's call gigabyte prix running Ubuntu Mate -> gigabyte and Synology machine -> synology. So how does gigabyte:/home/bruno/Videos relate to synology:/volume1/videos/movies? Note this has nothing to do with Docker... yet. If I was logged into on gigabyte in say a bash shell and did an ls /home/bruno/Videos would I see the same contents as if I was ssh'ed into synology and did an ls  /volume1/videos/movies? I think not. That's the first thing to get right. Then, the Docker volume mount would map the corresponding host's path to /media directory inside the container.

What I would do (and have done on my Synology and Ubuntu Mate desktop) is to use NFS to mount synology:/volume1/videos/movies -> gigabyte:/home/bruno/videos (or perhaps gigabyte:/home/bruno/videos/movies). NFS can be enabled on the Synology under Control Panel > File Services > NFS. You will also need a cache directory on synology and gigabyte similarly mounted (e.g. synology:/volume1/tdarr_cache -> gigabyte:/home/bruno/tdarr_cache). Note that since you are already running a Tdarr node locally on the Synology it has some sort of cache directory configured in the container. Use that same cache directory for the NFS mount to gigabyte too. Tdarr manages different cache files from different remotes so use the same directory for the cache.

Next, you're gonna want to get your Tdarr nodes to use hardware GPU transcoding in their Docker containers. They are much faster than CPU transcoding.

**Comment by 0brunoreis** [comment]
First, that seems to be backward. It should be :. So then that would be /home/bruno/Videos:/media.

I tried inverting it to no avail. in neither nodes.

My problem now is mounting the synology:/volume1/videos/ to linux. I eve, tried the app gigolo that automatically mounts drives every 30s but no difference.

I'll have to dig more. I even tried to modify sudo nano /etc/fstab

how did you mount your media shares in your synology? can you send some images so I can replicate?

thanks a bunch

**Comment by adefaria** [comment]
On the Synology, enable NSF
![2022-05-17@15:18:19](https://user-images.githubusercontent.com/2692127/168921614-59f1ab0b-ac8b-4f44-b71a-470c052e83ad.png)

I named my Synology Jupiter and my Ubuntu desktop Earth. On Earth in /etc/hosts I have:
```
Earth:grep jupiter /etc/hosts
192.168.0.251   jupiter
Earth:
```
In /etc/fstab I mount my media:
```
Earth:grep Media /etc/fstab
jupiter:/volume1/Media		/nas    	nfs defaults
Earth:
```
My media is under /volume1/Media on Jupiter. So ssh'ing into Jupiter it looks like this:
```
Jupiter:ls /volume1/Media
'@eaDir'/   Music/   Pictures/   Videos/
Jupiter:
```
On earth:
```
Earth:ls /nas
Music/  Pictures/  Videos/
Earth:
```
For convenience, I have symlinks like:
```
Earth:ll /Videos
lrwxrwxrwx 1 root root 11 Sep 29  2021 /Videos -> /nas/Videos/
Earth:
```
So once /etc/fstab is updated:
```
Earth:sudo mount -a
Earth:ls /Videos/Movies
10,000 BC (2008).avi
101 Dalimations (1996).avi
101 Dalmatians II Patchs London Adventure (2002).mp4
10 Things I Hate About You (1999).mkv
10 Years (2011).avi
10 Years (2011).en.srt
11 Minutes (2015).mkv
127 Hours (2010).mp4
12 Angry Men (1957).mp4
12 Men of Christmas (2009).mkv
...
Earth:
```
So then, /Videos is all my videos, /Music is all my Music, and /Pictures are all of my Pictures. I mount these to my desktop and my laptop and thus I have no duplication where I might have a song on my laptop that's not on my desktop or a picture on my desktop that's not on my laptop. And all of this is exposed to Plex so my videos, music and pictures are all "plexable".

When you have this mounted and can see your movies from your desktop, it's only a matter of  mapping it correctly into the Docker containers.

**Comment by 0brunoreis** [comment]
Amazing! I'll try that tonight. I hope I can set everything up correctly.

I'll let you know.

Once again, thank you very much

**Comment by adefaria** [comment]
Oops, I forgot some things! File systems need to be exported! You do this by editing /etc/exports on your Synology. Add a line to /etc/exports that correspond to the file system you want to export. Mine is /volume1/Media, yours is probably /volume1/Videos
```
/volume1/Media	192.168.0.0/24(rw,async,no_wdelay,no_root_squash,insecure_locks,sec=sys,anonuid=1025,anongid=100)
```
The above says to let every machine on the local LAN (your internal LAN - mine is 192.168.0.0/24, yours seems to be 192.168.1.0/24) be able to NFS mount this file system. Finally, export the file system by doing:
```
sudo exportfs -av
```
Editing of /etc/exports and doing the expportfs command need to be done through sudo. These steps only need to be done once.

Oh, and you may need to install nfs-common on your Ubuntu machine:
```
sudo apt install nfs-common
```

**Comment by 0brunoreis** [comment]
So I have been at it for 4 hours and this is what I did:

StorageB (my Synology NAS)
I enable NFS service and chose NFSv3 like you did.

ubuntu computer

installed nfs-common using the command:
sudo apt install nfs-common

sudo nano /etc/hosts
![Screenshot 2022-05-18 at 23 33 17](https://user-images.githubusercontent.com/98478473/169159459-e39194e3-0f28-4448-bf6b-8efc8caecb91.jpg)

now when I do, grep StorageB /etc/hosts, the following appears:
![Screenshot 2022-05-18 at 23 34 53](https://user-images.githubusercontent.com/98478473/169159699-d8bbb910-dd12-4f10-b320-5b65b35feca2.jpg)

then I typed grep video /etc/fstab and the following happened:

![Screenshot 2022-05-18 at 23 36 59](https://user-images.githubusercontent.com/98478473/169160101-aaa02d4f-1718-4e50-911e-6ab6dc1f72bd.jpg)

![Screenshot 2022-05-18 at 23 45 09](https://user-images.githubusercontent.com/98478473/169161112-d8b75f42-de3c-422d-8f63-8daf633ab360.jpg)

then I typed:
ls /synology to see if the folder /Volume1/video was mapped to the ubuntu machine's folder that I named Synology but I got a now access message:

![Screenshot 2022-05-18 at 23 48 51](https://user-images.githubusercontent.com/98478473/169161539-515df0b2-4e2d-4e97-a3d6-596bc9dda74f.jpg)

StorageB (my Synology NAS)
when I typed ls /volume1/video I was able to see its contents

ubuntu computer
I have no idea how to do the symlinks bit. I began by installing it with:
sudo apt install symlinks

then typed ll /synology and got a no access message:

![Screenshot 2022-05-18 at 23 59 16](https://user-images.githubusercontent.com/98478473/169162825-5012b100-9f78-4fe5-b163-2ade8cb692cc.jpg)

I guess I got this message because I haven't updated /etc/fstab but I don't know how.

StorageB (Synology)
couldn't't get into /etc/exports, permission denied.

![Screenshot 2022-05-19 at 00 03 55](https://user-images.githubusercontent.com/98478473/169163402-603ea44c-9cbe-4173-aa0c-2f3d4dde5c4a.jpg)

all of this to say that I am stuck...any guidance?

how do I get into symlinks and edit them?
why am I getting permission denied or cannot access?

thank you

**Comment by adefaria** [comment]
You must realize that Linux systems have a case **sensitive** file system. And the Synology is a Linux-based machine as is Ubuntu. As such be wary wherever you are dealing with filenames or filepaths. StorageB:/Volume1/videos is **not** the same as StorageB:/volume1/Videos! What you probably want in /etc/fstab is
```
StorageB:/volume1/video/Movies    /synology           nfs defaults
```
This is because you named the machine 'StorageB' in your /etc/hosts (I would have went with storageb or perhaps just synology) and the **case sensitive** file path relative to StorageB is /volume1/video/Movies (gotten from the screenshot of your Docker configuration posted long ago). IOW if you ssh'ed into StorageB and did `ls /volume1/video/Movies` you'd see your movies while `ls /Volume1/video` would show you nothing.

Also **IMPORTANT** the second field of /etc/fstab is an absolute filepath. "synology" is not an absolute filepath. `/synology` is. You need the leading '/' here.

Although you updated /etc/fstab I did not see a `sudo mount -a`. After updating /etc/fstab (fix the case and add the leading '/') you need to execute `sudo mount -a`. This tells mount to mount all filesystems listed in /etc/fstab, and you just added/corrected one. Then your `'ls /synology` should work.

Re: symlinks - they are not a package, they are part of the base OS. They come via the `ln` command (much like `ls` comes courtesy of the `ls` command. With all commands, `man ln`. Note Synology doesn't come with man pages but Ubuntu probably has them. Otherwise... Google "man ln". IOW you already have symlinks but for this exercise, you really don't need to symlink /Videos -> /synology or whatever. That's just a **convenience**. Work on that later.

You're getting closer but you need to just get the proper things connected together properly. Things like getting the spelling and case correct for computers are essential. Dealing with case-sensitive file systems really does not take that long to get used to. Just recognize that the file named "foo" and "Foo" as well as "fOO" and "FoO" are all different files - why? Because they are simply spelled differently. Then it all falls in line.

**Comment by 0brunoreis** [comment]
once again you were correct, like i said I am a noob.

now my /video folder mounts perfectly on both of my ubuntu boxes.

Synology
I tried to edit /etc/exports but was able and couldn't find a good tutorial.
I tried login in as root, then cat /etc/exports and then vi /etc/exports and added a line, the problem is that I don't know how to save. I don't have an option o do ctrl + X - yes then enter.

any tip?

**Comment by adefaria** [comment]
Noob's need to learn how to research. Surely you could have googled "how to save a file in vi". To save the file you'd type ":x" and return. Here's some instruction - https://phoenixnap.com/kb/how-to-vim-save-quit-exit

It is simple though - once in vi and not in input mode type ":x".

So `sudo vi /etc/exports` then type 'G" to go to the end of the file "o" to open a new line, paste or type in the new line, Esc to exit insert mode, and finally ":x" to write out the file and exit vi. Then do `sudo exportfs -av`.

However, you set that your /video folder mounts to your Ubuntu box so perhaps the exportfs is not necessary. Do you see the files you expect on Ubuntu when you `ls /video'? Is /video the name of the folder on your Ubuntu box that you NFS mounted StorageB:/volume1/video to? If so the Tdarr Docker container will need to do something like `-v /video:/video`. It's OK to have the path on the Docker host be the same name as the path in the Docker container because you use TDarr's WebUI to point to the source for a Library.

Also, don't forget to do that cache directory too.

Let me know if you need more help. I want to see you transcoding successfully!

**Comment by 0brunoreis** [comment]
I looked all over its hard to be precise when you don't know the name of what you are looking. Regardless, thank you for your support.

on my ubuntu machines I created a folder under /home/bruno/synology on one machine and /home/bruno/synovideos on the other.

before if I did ls /home/bruno/synology or synovideos I was able to see its contents now after editing vi I can't...

**Comment by 0brunoreis** [comment]
so I had to change part of the line like so:
/volume1/video 192.168.1.0/24(rw,async,no_wdelay,all_squash,insecure_locks,sec=sys,anonuid=1024,anongid=100)

with "no_root_squash" and "anonuid=1025"the following bits it was letting me access the mounted drives.
Is it a problem?

if I SSH into my ubuntu machines and type ls /home/bruno/synology I can see the contents of my /volume1/video (in my Synology). is there a problem that I have to add /home/bruno before /synology so see the folder's contents?

I tried once again:
docker exec -it tdarrnode-pve bash and docker exec -it hopeful-bell bash and got the following:

![Screenshot 2022-05-19 at 21 30 59](https://user-images.githubusercontent.com/98478473/169388289-a5bc4699-e23b-42ed-bb74-3e53e3933877.jpg)

![Screenshot 2022-05-19 at 21 31 07](https://user-images.githubusercontent.com/98478473/169388306-a89635a9-7f30-45d7-9bf5-87caf50268ad.jpg)

Tdarr still doesn't transcode. what a pain

docker volumes for both machines (yes it is normal that one is called /synology and the other /synovideos):
![Screenshot 2022-05-19 at 21 36 53](https://user-images.githubusercontent.com/98478473/169388582-7190f90d-6b1c-46e8-ba60-ad19af797655.jpg)

and second:

![Screenshot 2022-05-19 at 21 37 17](https://user-images.githubusercontent.com/98478473/169388679-c013551b-3abe-471c-beb7-8da083e06758.jpg)

**Comment by 0brunoreis** [comment]
I am kinda seriously contemplating going back to manually had files to handbrake on both machines...

**Comment by adefaria** [comment]
Re: no_root_squash - this essentially says that the root user on other machines will be treated as the root user on the machine where the file system resides. So in my setup, I can do things like `sudo chown 1000.1000 /Videos/TV/Show.mp4` on Earth where /Videos points to the NFS mount from my Synology. This addresses the security concern of "Hey you just mounted this file system to some client - do you really want them to simply become root on their system and start changing the files on the NFS file system you exported?". Normally you don't but hey, all of this is inside my house, I live alone and I know what I'm doing so yes no_root_squash for me. If that option were not specified then a "foreign" root user would be "squashed" to the anonuid (typically set to the "nobody" user or some "normal" user with little privileges).

While you did docker exec into your containers you did nothing when there. The exercise of doing docker exec was to verify that you can see your video files from **inside the container**. So do something like:
```
[bruno@birx-mate:~$ docker exec -it hopeful_bell bash
[root@215e4c69c7ac:/# ls /media
<Your media files should list here>
...
[root@215e4c69c7ac:/# exit
```
I'm assuming you have 3 machines here named StorageB (your Synology), Brix-mate (an Ubuntu desktop), and mate-pve (another Ubuntu desktop?). Also, I don't know why you're mapping /home/bruno/Documents/docker/tdarr/config to /temp. These are just temp or cache files. As Tdarr operates it transcodes a video from /media/SomeVideo.mp4 -> /temp/SomeVideo.mp4. After it finishes and possibly performs a health check to make sure the file is OK it moves SomeVideo.mp4 from /temp back to /media. So I might map /home/bruno/tdarr_cache -> /temp or something like that. I mean you could use the path you used but I would put it somewhere outside of the config dir because to me config means configuration data, not cache/temp data.

I am assuming that:

- From an ssh session on StorageB (your Synology) you can do an `ls /volume1/video and see your videos and
- From an ssh session on brix-mate you can do an `ls /home/bruno/synovideos` and see those same videos and
- From an ssh session on mate-pve you can do an `ls /home/bruno/synology` and see those same videos

We know that your NFS mounts are good.

Further, if we do:

- From an ssh session on StorageB you can do `docker exec -it tdarr_server ls /media` and your videos and
- From an ssh session on brix-mate you can do `docker exec -it hopeful_bell ls /media` and see those same videos and
- From an ssh session on mate-pve you can do `docker exec -it tdarnode-pve ls /media` and see those same videos

(Note the last parameter to docker exec is the command to run. You need not run a bash shell and then do the ls, you could just do the ls as I have above).

Personally, I settled on naming my docker containers tdarr_server for the server and tdarr_node for all of the other machines. This way I don't have to remember that I named the container hopeful_bell on this machine and tdarnode_pve on the other machine. It's either tdarr_server or tdarr_node depending on what the container is doing in the container.

If the above is true then we know that the docker containers can see the files they need to operate on. Then go into Tdarr's WebUI and create or reconfigure a library whose Source is `/media and Output folder is `/temp` and perhaps do `Options -> Requeue all items (transcode)`.

Another benefit of setting this up and leaving the docker containers running is that when you add new videos to your collection Tdarr will sense them and transcode them (provided you toggled on `Folder watch` for the library.
