### ISSUE TITLE
Tdarr making videos larger when compressed and/or never finishing

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#621]
**Describe the bug**
There are times when Tdarr never seems to finish compressing videos. It says it's going to make the file bigger than the original size then seems to reprocess the file adding on a -map 0:&lt;n+1&gt;. This process seems to continue again and again never finishing nor giving up saying "since I can't make it smaller, I'll leave it alone".

**To Reproduce**
Transcode files, watch them never complete

**Expected behavior**
I expected it to either compress the file and save some space or give up and leave it alone so that it can work on another video.

**Screenshots**
![2022-05-09@10:57:46](https://user-images.githubusercontent.com/2692127/167497905-fdf45664-7318-42f8-96e4-16133cfc9494.png)

Notice that the estimated final size is slightly bigger than the original size. Also, notice that there are 69 -map options

![2022-05-09@11:02:43](https://user-images.githubusercontent.com/2692127/167498141-be3609c7-7502-4ebd-9b72-0af4e852e4be.png)

Notice here it's trying again with -map 0:70 this time!

![2022-05-09@12:27:38](https://user-images.githubusercontent.com/2692127/167498289-f623ad47-7353-499b-ac6f-45729cfed42c.png)

Here's an example of Tdarr wanting to expand it by more than twice the original size!

**Please provide the following information:**
- Config files 
```
{
  "nodeID": "Earth",
  "nodeIP": "192.168.0.102",
  "nodePort": "8268",
  "serverIP": "192.168.0.251",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "platform_arch": "linux_x64_docker_true"
}
```

- Log files 

Nothing in the logfile mentions this video (Kansas).

-Worker error
Since the video never finishes there is no Worker error to see.

- OS: Ubuntu 21.10 (though I'm running it in a docker container)
- Browser N/A
- Version 2.00.15

**Comment by supersnellehenk** [comment]
I can't comment on the mapping part, I know the issue is it's mp4. I do remember HGG pushing out an update for the plugin for that, could you try a force update from the UI? I also can't help but notice that you're running 2.00.15 while 2.00.18 is the latest version. Not that it would make a difference.

The 'twice the original size' thing is weird because it has sped through that entire file in 11 seconds for a 1,5-hour movie, which doesn't seem correct.

**Comment by adefaria** [comment]
How does one "force an update from the UI"? Note I'm running in a docker container...

**Comment by supersnellehenk** [comment]
Certain actions will cause the file to grow a little bit in size, a remux could be ffmpeg correcting errors in the container.

Tdarr doesn't automatically cut off transcodes.

You should also stop looking at the estimated output size when you're below like 50% through the file, depending on the action happening. The estimate can fluctuate a whole lot, especially early into an action.

**Comment by adefaria** [comment]
I can live with a little filesize growth. But I've seen growth or more than double. Thanks for pointing me to not taking such things that seriously until 50% or so has been processed, though it might be nice if the percentage was listed on that screen. It's just I've seen transcode errors in about 50% of the videos and I've seen certain videos getting stuck with long -the map's being added on. Then witnessed them adding on another -map and redoing the transcode. All I could think is "When is this gonna stop?".

For example, I have 3338 movies and 1687 of them are listed as transcode errors. Now they may be errors for many different reasons (speaking of which it'd be really nice if we could easily download a list of all the error files grouped by error message so we can then attack them by groups as we solve problems) but I also saw many files being seemingly stuck in this loop of failing and adding another -map option.

In the end, I'm just trying to figure out how to push the remaining videos through Tdarr and understand and fix the transcode errors.

**Comment by HaveAGitGat** [comment]
Hi please post the job reports containing the errors you need help with. As snell mentioned, the above issue is not a transcode, it's remux which causes slight variations in file size. 

Tdarr plugins auto update every hour so there's most likely no need to force update but you can use this button:

![image](https://user-images.githubusercontent.com/43864057/168514457-cc6d13d1-f768-4525-ae3f-34b437c92d61.png)

FFmpeg can struggle when re-ordering streams of mp4 files so try using this plugin instead of reorder streams v2: Tdarr_Plugin_lmg1_Reorder_Streams
