### ISSUE TITLE
Filename too longh when creating CacheFile

### ISSUE THREAD

**Issue by techie2000** [HaveAGitGat/Tdarr#631]
**Describe the bug**
A sub-worker can fail when the source filename is 'long' and it tries to add the -TdarrCacheFile-PjEPTIWqWB.mkv type suffix resulting in the max length a filename being exceeded

**To Reproduce**
Run a job that will result in a sub-worker performing an action (and thus generate a temp file) on a filename that is very long to begin with, e.g.`blahs (1979) {imdb-tt0012345} - Theatrical Edition - [2160p] [HDR] [10bit] [6ch, 2ch, 2ch, 6ch, 6ch, 6ch, 6ch, 6ch] [Opus, Opus, Opus, Opus, Opus, Opus, Opus, Opus] [eng, eng, eng, spa, fra, deu, ita, rus] [AV1] [3840x1600] [240-1].mkv`

**Expected behavior**
sub-worker will process work and not die due to a trappable system error

**Screenshots**
n/a

**Please provide the following information:**
- Config files 
```
{
  "nodeID": "Redacted",
  "serverIP": "192.168.1.115",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "platform_arch": "linux_x64_docker_true",
  "logLevel": "INFO"
}

{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "192.168.1.115",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO"
}
```

- Log files 
`2022-05-19T10:39:54.794Z /temp/blahs (1979) {imdb-tt0012345} - Theatrical Edition - [2160p] [HDR] [10bit] [6ch, 2ch, 2ch, 6ch, 6ch, 6ch, 6ch, 6ch] [Opus, Opus, Opus, Opus, Opus, Opus, Opus, Opus] [eng, eng, eng, spa, fra, deu, ita, rus] [AV1] [3840x1600] [240-1]-TdarrCacheFile-PjEPTIWqWB.mkv: File name too long`
(certain text redacted/replaced for bug report)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Linux
 - Browser Edge
 - Version 2.00.18

**Additional context**

**Comment by adefaria** [comment]
Under Linux, the length of a filename is limited to 255 characters. A simple work around would be to rename the source file (I really don't think you need "Opus, Opus, Opus, Opus, Opus, Opus, Opus, Opus" for example).

**Comment by techie2000** [comment]
> Under Linux, the length of a filename is limited to 255 characters. A simple work around would be to rename the source file (I really don't think you need "Opus, Opus, Opus, Opus, Opus, Opus, Opus, Opus" for example).

The filename includes all channels, codecs, and languages, of which there are a lot in this file, hence the long, but legitimate, name.
For me, the bug report is not about the choice of naming convention is not the issue, it's about how the process handles something legitimate?. I could have called it "this is a very long filename which fits with my preferred methodology of for naming my stuff even if nobody else likes it, it is my prerogative and a legitimate filename.mkv", and I have a colleague who names his files with the film name + original film name + the original foreign name as well, so some of his get very long, and have no apparent repeated info. It's personal preference. What I'm trying to convey is the filename/length shouldn't cause issues with the workflow as 'you' have no control of what users will throw at it.

Possible coding change workarounds would be creating a (temp) folder that is the original filename and then using a randomly generated filename for the temp file inside it (like the suffix that is added today, TdarrCacheFile-PjEPTIWqWB.mkv), allowing for an easy rename back and cleanup at the end and without the need to track a variable that is the original name.

**Comment by rjwaters147** [comment]
I am also having this same issue running Tdarr docker container on Unraid 6.10.2

**Comment by taw123** [comment]
On the chance it it's helpful to know, the issue remains (though you likely know this, since it's marked open)... And that there is another person who also has a number of files it seems that are failing transcode cache naming because of file to long error. (Platform: Docker/Linux - NOT hosted on unRAID- not that it has anything to do with the error of course).

Thanks for all the work on this project. A quick followup question....   Looking for potential query access to the native database (to not only find those transcodes that failed (by error type, file size, etc). More complex querying than seems possible via the simple search interface via the web front end (don't suppose I can enter a regex query and/or quoted and special value (i.e. test for null, 0, etc)?

All the best and if I can help in any way with this please let me know. Was a software engineer for 20 years before turning to Product Management years ago at a famous "fruit" company here in the SF Bay Area 😉

--Tom

**Comment by Enlinks** [comment]
I would like to also confirm I am having this issue. Currently at the moment I've only see the issue with 1 series but I'm sure there are other Anime series (and use cases) for having extremely long names.

The series I'm currently having issue with is "The Disastrous Life of Saiki K.", file name example:

Pre cache:
"The\ Disastrous\ Life\ of\ Saiki\ K.\ -\ S02E18\ -\ Touma\ Akechi,\ the\ Transfer\ Student\ Who\ Never\ Shuts\ Up\ +\ The\ Transfer\ Student's\ Still\ Talking!\ +\ Sweet\ Potato\ Digging\ Disaster\ +\ Putting\ the\ Mascot\ Characters\ in\ Order\ +\ Metori\ Saiko's\ Listless...\ Bluray-1080p.mkv"

Tdarr Failure:
"The Disastrous Life of Saiki K. - S02E18 - Touma Akechi, the Transfer Student Who Never Shuts Up + The Transfer Student's Still Talking! + Sweet Potato Digging Disaster + Putting the Mascot Characters in Order + Metori Saiko's Listless... Bluray-1080p-TdarrCacheFile-nfRQqOYf-2.mkv"

According to trakt.tv it looks like my original file name is already cut off due to the addition of the "Bluray-1080p". So it seems that Sonarr preemptively stripped the end of the episode name in order to accommodate the max character length restriction of the filename.
"Touma Akechi, the Transfer Student Who Never Shuts Up + The Transfer Student's Still Talking! + Sweet Potato Digging Disaster + Putting the Mascot Characters in Order + Metori Saiko's Listless Days"
https://trakt.tv/shows/the-disastrous-life-of-saiki-k/seasons/2/episodes/18

**Comment by HaveAGitGat** [comment]
Suppose solutions would be to change the cache file syntax to be shorter so something like `tcf-PjE` instead of `TdarrCacheFile-PjEPTIWqWB` or make no changes to the filename and instead store each file in its own subfolder:

`/temp/TdarrCacheFile-PjEPTIWqWB/example video nam.mp4`


@taw123 thanks for the support :).  You can interact with the db using this endpoint:

https://tdarr.readme.io/reference/post_cruddb

Example here:

https://github.com/HaveAGitGat/Tdarr/issues/752#issuecomment-1472621551

ChatGPT can have a go at converting into whatever language you need.

Unfortunately no regex atm so would need to loop through and check each document individually.

**Comment by HaveAGitGat** [comment]
Fixed in Tdarr Flows as it uses the original filename with no extra stuff when creating the cache file.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/d3733c30-25ff-43ff-9979-ea354f408c6a)
