### ISSUE TITLE
Continuing: Ok keeping it simple.

### ISSUE THREAD

**Issue by tmyflyte** [HaveAGitGat/Tdarr#636]
Hi, I'm sorry to bring this topic up again, but I can't see the Force processing option (I'm on Tdarr 2.00.18 running on unraid)

My case: I did a test run using CPU transcoding of a backup folder, now I want to run all the original files using GPU transcoding but the filenames are the same. They're automatically moved to the Error/Cancelled tab

---

Ok keeping it simple.

All new plugins created in the next version will have a new forceProcessing switch which overrides the filter:

![image](https://user-images.githubusercontent.com/43864057/70171035-d53af280-16c5-11ea-99fc-a5a8ab7f0117.png)

Force processing can be set in the queue or in the 'Search' tab:

![image](https://user-images.githubusercontent.com/43864057/70171074-e7b52c00-16c5-11ea-9c83-61434d6cca2e.png)

It will allow for the FIRST plugin filters in the plugin stack to be overriden. It is best practice to have the transcoding plugin at the top of the stack anyway.

So a typical stack might look like:

Transcode using HandBrake
Remove subs
Remove closed captions

The force processing will force the handbrake transcode and then the status for force processing is reset.

_Originally posted by @HaveAGitGat in https://github.com/HaveAGitGat/Tdarr/issues/87#issuecomment-561785304_

**Comment by HaveAGitGat** [comment]
Hi the forceProcessing option from V1 was removed in V2 as it didn't really work (or only in certain cases) so it was more confusing to keep it in.

Which plugin are you using?

**Comment by tmyflyte** [comment]
Thanks for the response. I'm using these:

![image](https://user-images.githubusercontent.com/24412030/169886506-095d7cd2-eb26-40b7-a50a-940adf9a1ea4.png)

**Comment by HaveAGitGat** [comment]
Plugins are conditional so you need to add some conditions so that Tdarr knows the file is as you require.

So the Migz plugin is checking if the file is hevc or not and transcoding based on that.

So in your case you could use metadata, bitrate, size or something other than codec to say if the file needs to be processed or not.

All the plugin are inspecting the file and producing transcode arguments based on the conditions. So it's not possible to force processing with those plugins as they won't product any transcode arguments as the file already meets the conditions.

**Comment by HaveAGitGat** [comment]
Re-open if needed.
