### ISSUE TITLE
Transcoding on an Xbox?

### ISSUE THREAD

**Issue by cat007mine** [HaveAGitGat/Tdarr#644]
Hi all.
Is there a way to use the Xbox Series S CPU/GPU to transcode media?

**Comment by Kazz3r24** [comment]
I'm doubting it, unless you can install tdarr_node on it.

**Comment by ToasterUwU** [comment]
@cat007mine Nope. Xbox doesnt allow to use any software that isnt approved by Microsoft, and even if Microsoft is like "Ohh yeah, lets allow this console only program for transcoding videos", it wont work since you cant just run a .exe on an Xbox.

Talking about other devices than a PC for Tdarr.. Can i somehow use my Gucci smart toilet for transcoding?

**Comment by cat007mine** [comment]
> @cat007mine Nope. Xbox doesnt allow to use any software that isnt approved by Microsoft, and even if Microsoft is like "Ohh yeah, lets allow this console only program for transcoding videos", it wont work since you cant just run a .exe on an Xbox.
> 
> Talking about other devices than a PC for Tdarr.. Can i somehow use my Gucci smart toilet for transcoding?

Ok thanks - was worth a shot. Seems like a lot of wasted hardware sitting there doing F all most of the time.

Check with your butler re: Gucci toilet.

**Comment by Kazz3r24** [comment]
Did you not see the latest announcement of all the games coming to Game Pass? 2022-23 will be amazing years to be an Xbox owner lol.

**Comment by ToasterUwU** [comment]
@cat007mine Yeah. If you got an old laptop, you could that one for transcoding as well.

Btw, if you are done with this issue, you can close it. Would save the creator of Tdarr reading this and closing it on their own.
