### ISSUE TITLE
MP4 to M3U8/TS but only M3U8 moved from cache

### ISSUE THREAD

**Issue by frontdelt** [HaveAGitGat/Tdarr#698]
**Describe the bug**
I have written a simple plugin to convert mp4 to m4u8/ts using ffmpeg. In the cache folder, m4u8 and ts file were created but in (Step S02) of report, I read that only the m3u8 file is moved from cache to my output folder.

**To Reproduce**
Heres the preset of my plugin response to output m3u8 and ts from mp4 container
response.preset = '<io> -codec: copy -start_number 0 -hls_time 10 -hls_list_size 0 -f hls ';
	

**Expected behavior**
Any chance those ts files in cache are moved to output folder as well?

**Additional context**

**Comment by HaveAGitGat** [comment]
Please post full plugin ty

**Comment by intrapt** [comment]
Here's a plugin that (should) reproduce the described behaviour: https://gist.github.com/intrapt/b338db01e46bfdcd4196b6eddf726585
It's worth noting that it's possible to write the segment files directly to the source directory (or output folder) like this: https://gist.github.com/intrapt/6f288f02515088476f14551716c0c65f

**Comment by HaveAGitGat** [comment]
Ok can use that solution or we could update Tdarr Flows plugin to do this, will handle here if needed:  https://github.com/HaveAGitGat/Tdarr_Plugins

So could update the 'Move To Directory' or 'Copy To Directory' plugins so that they copy all files in folder.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/4262af34-ebc1-4429-b1fd-268b12cff158)
