### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by Xe138** [HaveAGitGat/Tdarr#7]
I've been getting the following fatal error since updating yesterday.

`MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongodb mongodb:27017]`

It's possible something went wrong before the update, as it didn't seem to be transcoding anymore.  I tried removing the database files and updating again, hoping it would rebuild, but I got the same error.

**Comment by HaveAGitGat** [comment]
@Xe138 

Please see the new setup instructions. You need to install pull and run the MongoDB container separately. This so that if multiple programs use MongoDB then everything is now in one place rather than having lots of MongoDB instances. Apologies for the inconvenience. I was wanting to do this as soon as possible before more people start using the application.

**Comment by Xe138** [comment]
Got it.  I already have a MongoDB instance running, so this is a good change.  Thanks.
