### ISSUE TITLE
Transcodes failing without reason

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr#729]
I have been facing this issue for a while now and have not been able to figure it out. I have been using TDARR for a few years and within the last year or so, transcodes will randomly fail and there will be no specific error given. It can happen anywhere from a few seconds into the transcode to a few seconds left. Requeuing the failed file generally succeeds in the next attempt.

I am unable to find anything about the files that fail in terms of what they have in common. It seems to be completely random. Whether I have a large queue, or just a few files. I have also tried changing plugins, but this doesn't appear to have an impact either. I also get the same failures when I test on a separate node as well.

Currently, I am using the Tdarr_Plugin_vdka_Tiered_CPU_CRF_Based_Configurable community plugin

Error message
`211 2022-12-09T19:43:15.144Z frame=58813 fps= 13 q=25.3 size= 690432kB time=00:32:42.81 bitrate=2881.6kbits/s speed=0.424x
212 2022-12-09T19:43:15.144Z frame=58820 fps= 13 q=21.7 size= 690432kB time=00:32:43.02 bitrate=2881.3kbits/s speed=0.424x
213 2022-12-09T19:43:15.144Z frame=58828 fps= 13 q=21.1 size= 690432kB time=00:32:43.32 bitrate=2880.8kbits/s speed=0.424x
214 2022-12-09T19:43:15.144Z frame=58834 fps= 13 q=20.0 size= 690432kB time=00:32:43.45 bitrate=2880.6kbits/s speed=0.424x
215 2022-12-09T19:43:15.144Z
216 2022-12-09T19:43:15.158Z RBIYwI9xXJG:Node[MainNode]:Worker[5EuvuGum6]:[-error-]`

I am running docker container of TDARR server and node workers of 2.00.18. 

Anyone have any advice. I am getting tired of this as I am wasting quite a bit of extra power on the transcodes that are just failing and I have to start them over again.

**Comment by HaveAGitGat** [comment]
Do you have the full job report? Testing new FFmpeg versions at the moment so will release 2.00.19 once that's done. Perhaps that will fix the issue.

**Comment by HaveAGitGat** [comment]
Thanks, from what I can see this is because FFmpeg is not giving an exit code when it closes: `CLI code: null`

Should be giving code 0 for a successful run or a different number if there's been an error. So yeah can only hope it's fixed in the new version of FFmpeg.

Could try these builds from today:
docker pull haveagitgat/tdarr_acc:dev_2.00.19_2023_02_03T18_52_13z
docker pull haveagitgat/tdarr_node_acc:dev_2.00.19_2023_02_03T18_35_24z

**Comment by clifford64** [comment]
Any idea when those dev builds are going to be merged and published into the latest release?

**Comment by HaveAGitGat** [comment]
Been writing tests this week to make sure things are working as expected. Got 5-10 hours worth of stuff to go and can then move towards .19 release. Will be checking things with a few other people this weekend.

**Comment by HaveAGitGat** [comment]
2.00.19 released, reopen if needed thanks

**Comment by clifford64** [comment]
Still the same issue on 2.00.19

**Comment by drewstreib** [comment]
I have the same issue on current builds. I'm experimenting with some variables (such as using local directories for tmp cache) to see if I can isolate the behavior. Note this is on docker.

**Comment by clifford64** [comment]
> I have the same issue on current builds. I'm experimenting with some variables (such as using local directories for tmp cache) to see if I can isolate the behavior. Note this is on docker.

I never found the issue causing this. I am using docker as well. I am still experiencing this issue. I tried redoing my entire Tdarr setup as well and it's still happening. My storage is on my network that is mounted locally to the device and then passed thru to the container. It's a 10gb connection and never had any problems with it.

**Comment by drewstreib** [comment]
Over the next week I'm going to try:

1) Purely local (to the docker host) temp storage.
2) docker run tdarr server, but moving a processing node to a local host thing rather than in a container
3) smb mounting the temp directory instead of NFS? (If (1) works. Just to see if there could be something in the mount behavior.)

As this issue is intermittent (but shows up within 20-30 transcodes nearly every time), it might take me a few days each to determine if any of this makes the symptom go away.

**Comment by drewstreib** [comment]
So it isn't the network mounted tmp directory. Had the same failure with local tmp storage. Next to try a worker that isn't containerized.

**Comment by drewstreib** [comment]
intel i9-13900, doing cpu only encodes.

**Comment by drewstreib** [comment]
So this apparently is solved by not using the ghcr.io/haveagitgat/tdarr:latest container for the worker node. I've kept the container as the controller and moved worker off to the native linux binary running on Ubuntu 22.04, and the problem has gone away. I might try rolling my own container to see if this fixes things, but I don't see anything inherently wrong with the official Dockerfile.

I'm going to guess some kind of failure to allocate memory or something odd on an individual ffmpeg worker, causing it to crash, even though this particular machine has plenty and is not under pressure at all. But I can't think of another good reason why ffmpeg would just crash randomly. 

So *something* container related, although seemingly random, on an otherwise stable machine with plenty of available RAM. 

(Only other possibility is that the ffmpeg binary in that container is flawed, but the random nature of the crashes and the fact that re-attempts succeed, make me steer away from this.)

**Comment by drewstreib** [comment]
I should mention that this is stock Ubuntu 22.04, with stock 'docker.io' install and docker-compose launching the container(s).

**Comment by clifford64** [comment]
> So this apparently is solved by not using the ghcr.io/haveagitgat/tdarr:latest container for the worker node. I've kept the container as the controller and moved worker off to the native linux binary running on Ubuntu 22.04, and the problem has gone away. I might try rolling my own container to see if this fixes things, but I don't see anything inherently wrong with the official Dockerfile.
> 
> I'm going to guess some kind of failure to allocate memory or something odd on an individual ffmpeg worker, causing it to crash, even though this particular machine has plenty and is not under pressure at all. But I can't think of another good reason why ffmpeg would just crash randomly.
> 
> So _something_ container related, although seemingly random, on an otherwise stable machine with plenty of available RAM.
> 
> (Only other possibility is that the ffmpeg binary in that container is flawed, but the random nature of the crashes and the fact that re-attempts succeed, make me steer away from this.)

I also only have the tdarr server container and set it up so the node is also within the container. So it could be the version of ffmpeg they are using that is causing the instability. I have 8gb of ram assigned to the VM that the containers run on and running a transcode only uses about 6gb and I have 2 free.

**Comment by HaveAGitGat** [comment]
@drewstreib @clifford64 what you could try is increasing the FFmpeg log level. For example could add `-v debug` to your FFmpeg commands and click to log full CLI output on the Tdarr tab.

Would result in large logs but might show what’s going on.

**Comment by clifford64** [comment]
> @drewstreib @clifford64 what you could try is increasing the FFmpeg log level. For example could add `-v debug` to your FFmpeg commands and click to log full CLI output on the Tdarr tab.
> 
> Would result in large logs but might show what’s going on.

I've already tried this.i believe that is what the output logs above are. The device logs don't appear to show anything different and ffmpeg just exits with no other information. I also tried running the same ffmpeg command manually within the container itself and the error it was throwing was "segmentation fault: core dumped."
