### ISSUE TITLE
Feature Request: Keep Original Source File

### ISSUE THREAD

**Issue by svindled** [HaveAGitGat/Tdarr#784]
**Is your feature request related to a problem? Please describe.**
By default Tdarr replaces source with transcoded file.

**Describe the solution you'd like**
I have a plex library that I share with family - I'd like to be able to provide lower quality versions to make it easier for them to stream (sometimes they struggle to stream some of the 4K content I have). I'd like to be able to have Tdarr mass convert (at first) versions to store inside the source folder rather than replace the higher quality version.

**Describe alternatives you've considered**
Having a separate 1080p library maybe? Seems like it would be a pain to manage though.

Thank you :)

**Comment by RoboMagus** [comment]
I'd love this feature too!

I've been looking for a way to implement this myself using a plugin, but there does not seem to be any handles to hook into.
Additionally, one would have to figure out a way to prevent the source file from being processed again next time, as it would continue to qualify for being transcoded.

**Comment by HaveAGitGat** [comment]
@RoboMagus yeah that's one of the issues. Tdarr was designed so that you have all your files scanned in your libraries and the original files are replaced when processing is done. Having multiple version of the same file is possible but not quite in line with the flow of things. It's technically possible using plugins in that you could do the ffmpeg execution within the plugin yourself instead of returning arguments. Could then use file metadata to keep track of what's the original file and what are the processed files.

So new file comes in, in plugin tag VERSION metadata as `original`, if say `720p` and `420p`  version don't exist create them and tag with VERSION `720p` and `480p` with that added to the filename too.

Those new files will then be picked up by Tdarr and will go through the plugin, it will see VERSION metadata is not `original` and not do anything with them. Something like that.

**Comment by rodhfr** [comment]
this is exactly what I need. waiting for this feature since I don't know any code at all 😁

**Comment by HaveAGitGat** [comment]
Added a flow template to do this, you can try it in tdarr 2.10.02, can edit as needed:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/3d91bf2b-c695-4b70-b65a-c6ac60695c35)

**Comment by HaveAGitGat** [comment]
Beta released the other day so should be working fine.
