### ISSUE TITLE
CPU Spikes

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr#83]
I was monitoring my CPU when I noticed some strange spikes every 15 seconds while tdarr is not doing anything. I am just wondering if this is normal? Below is a screenshot of the process that is causing the spike. To clarify, when I say spike, I mean a 10-20% spike. My server is not doing anything else and before Tdarr, it was not spiking like this. It seems to pertain to node.js, but I have no experience with that.
![image](https://user-images.githubusercontent.com/32966295/69843683-b3a9b900-1236-11ea-9781-99cfc27adf62.png)

Here is an image of the spikes itself.

![image](https://user-images.githubusercontent.com/32966295/69843713-c7551f80-1236-11ea-82e0-938662d26c90.png)

**Comment by theg00s3** [comment]
It might be library scans, but that does seem excessive

**Comment by clifford64** [comment]
From what I saw when I did quick research, node.js is a scripting language for JavaScript. Is that what tdarr is built off of? Or is there a specific part of tdarr that utilizes node.js that I can look into further to try and narrow this down.

**Comment by HaveAGitGat** [comment]
@clifford64 this isn't to do with the file scanner, it's to do with re-calculating all the queues every 15 seconds or so which can become more processor intensive the more files you have (I'm guessing you have around 14000 files or so). For example here's mine:

![image](https://user-images.githubusercontent.com/43864057/69885177-d6d67600-12d3-11ea-9cd7-c9cf65db53fb.png)

I'm working on fixing this.

**Comment by clifford64** [comment]
Closer to 8000

**Comment by HaveAGitGat** [comment]
@clifford64 not at then moment. It’s based on the number of files you have have in your library (1 second added for every 1000 files).

**Comment by HaveAGitGat** [comment]
Fixed for 1.008

**Comment by HaveAGitGat** [comment]
I've spent a few hours optimising things further, here are the results:

Before:

![CPUPre](https://user-images.githubusercontent.com/43864057/69905231-8715ae80-13a8-11ea-9842-92987729f017.PNG)

After:
![image](https://user-images.githubusercontent.com/43864057/69905224-80873700-13a8-11ea-890a-63c88e86ab2b.png)

[1] Is the area which as been improved. Now Tdarr only carries out queue operations when it really needs to, instead of all the time as before.

[2] This is the folder watcher which polls the disk every 30 seconds.

[3] Is with folder watcher turned off and Tdarr not needing to do any queue operations.

So now when Tdarr is idle with folder watch on it has little spikes of 19%/800% every 30 seconds or so instead of spikes of 100%/800% every 10-15 seconds from before.

This improvement is in the tdarr_dev container (same settings as tdarr_aio) if you want to use it immediately.

**Comment by HaveAGitGat** [comment]
1.008 released
