### ISSUE TITLE
Feature Request - Force Transcode

### ISSUE THREAD

**Issue by Wdavery** [HaveAGitGat/Tdarr#87]
There a few files of mine that slip past my transcoder, because they match the general requirements, but I'd like to run them through for one reason or another.

I'd love a 5th option to go with Codec/Size/Height/Width such as Forced, and just be able to flag the odd file manually.

**Comment by HaveAGitGat** [comment]
@Wdavery 

This type of thing has been requested a few times in different ways.

The good thing about Tdarr at the moment is that if you accidentally delete all your Tdarr data, then when you set everything back up, files that are already in the required codecs won’t be transcoded again. Duplicate transcoding is prevented. 

I understand there are times when you want to force transcoding of a particular file. For example you might have a 10GB hevc file which you’d like to reduce down to 2-3GB by transcoding again into hevc.

The issue is keeping track of what has already been force transcoded. For example, there are several ways:

1. Create a plugin which, after the file has been force processed, saves the file name to a text file. If/when the file is requeued, the plugin reads the text file to see if the file has already been force processed. This way the user has a log of what has been force processed already. A button can be added in the UI to set force processing. If Tdarr is deleted, a backup can be restored. 

2. Similar to the above, except the database is used instead of the text file to keep track of what has been processed. Not as favourable.

3. (What you suggest) No log is kept, instead a simple button in the UI is used to set a file for forced processing. This is used with a ‘Forced processing’ filter in the plugin creator. Once a file has been processed, its forced processing status is reset so in future it won’t be force processed again. The user will have to remember which files they have force processed as no list is kept.

Open to suggestions.

**Comment by Wdavery** [comment]
Hmm you bring up a good point about keeping track, especially in a reinstall situation. 

I think in this case because it is such a manual process, you don't need to worry about keeping a record of the transcoded files. 
Forced in it's very nature throws out all the logic rules anyway. There's no reason (according to the filters) that these files should be processed, but the user has decided to ignore that and go ahead anyway. 

I think it's best to keep it super simple for this feature, but I'd like to see what other people think as well.

**Comment by HaveAGitGat** [comment]
Ok keeping it simple.

All new plugins created in the next version will have a new forceProcessing switch which overrides the filter:

![image](https://user-images.githubusercontent.com/43864057/70171035-d53af280-16c5-11ea-99fc-a5a8ab7f0117.png)

Force processing can be set in the queue or in the 'Search' tab:

![image](https://user-images.githubusercontent.com/43864057/70171074-e7b52c00-16c5-11ea-9c83-61434d6cca2e.png)

It will allow for the FIRST plugin filters in the plugin stack to be overriden. It is best practice to have the transcoding plugin at the top of the stack anyway.

So a typical stack might look like:

Transcode using HandBrake
Remove subs
Remove closed captions

The force processing will force the handbrake transcode and then the status for force processing is reset.

**Comment by Wdavery** [comment]
I think that's a great implementation. Thanks!

**Comment by ansuz07** [comment]
@HaveAGitGat - was this feature lost in V2?

**Comment by tmyflyte** [comment]
Hi, I'm sorry to bring this topic up again, but I can't see the Force processing option (I'm on Tdarr 2.00.18 running on unraid)

My case: I did a test run using CPU transcoding of a backup folder, now I want to re-run all the original files using GPU transcoding but the filenames are the same. They're automatically moved to the Error/Cancelled tab

**Comment by HaveAGitGat** [comment]
@tmyflyte responded to your other message
