### ISSUE TITLE
FLOWS transcode plugin does not use hardware (can't reopen)

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#875]
Sorry for reopening this but everything seemed to work for days, until now:

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/4650021e-5d78-49a7-8095-c01e9ed7968a)

I went to that node and tried the command to check QSV (got it from the logs):

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/181f9ed1-c7ba-4ebe-9c78-c113a61addb1)

From what i can see, besides the 2 warnings, the command worked fine, but the logs for the plugin that checks hardware, repoted that it didn't detect QSV:

```2023-10-09T14:59:06.153Z b0k2aBtyT:Node[smo105test]:Worker[brief-bug]:Checking for encoder hevc_qsv with command:
2023-10-09T14:59:06.153Z b0k2aBtyT:Node[smo105test]:Worker[brief-bug]:C:/Users/MC Retail/Desktop/Tdarr/Tdarr_Node/node_modules/ffmpeg-static/ffmpeg.exe -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_qsv -load_plugin hevc_hw -f null /dev/null
2023-10-09T14:59:06.153Z b0k2aBtyT:Node[smo105test]:Worker[brief-bug]:Encoder hevc_qsv is disabled
```

**Comment by HaveAGitGat** [comment]
I think this is maybe to do with the warning which is being output on stderr (error output).

I've updated it so it uses a different way of checking if the command was successful: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/504/files

Let me know if you still have trouble and I'll reopen ty.

**Comment by Kedryn** [comment]
[tc-k3NNad-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12936871/tc-k3NNad-log.txt)
another user-case of qsv not detected, right now

**Comment by HaveAGitGat** [comment]
@Kedryn how many encodes do you have going at once? If you've reached the limit then the qsv command will fail.

To be clear, the `detection` just runs a quick test of ffmpeg on a tiny virtual file. It's not checking OS hardware info or anything like that (as at plugin run time it could be the case that the machine has the correct hardware but ffmpeg would fail during the encode due to encode limit being reached).

You can see in the log the command being run so try running that command manually and if you need the command to be modified slightly then let me know.

If still having trouble then feel free to reopen on https://github.com/HaveAGitGat/Tdarr_Plugins as this is plugin related.

**Comment by Kedryn** [comment]
I had 3, but all 3 where CPU (because of failed QSV test)
recently, this problem is limited only to 1 node, maybe beacause all your fixes

Right now, it's going in QSV. As soon as i see it doing CPU again, i'll try running ffmpeg myself to check results

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/b5229d66-f979-4139-88ac-0eccdb0cbfe1)
