### ISSUE TITLE
Base URL env.json doesn't work

### ISSUE THREAD

**Issue by theg00s3** [HaveAGitGat/Tdarr#90]
The env.json workaround, as mentioned in #51 doesn't work properly. After the file is created, the base url will appear in the options tab, but the actual url won't change unless you change the base url from the options tab. 

This is in tdarr_aio by the way

**Comment by HaveAGitGat** [comment]
@theg00s3 I believe the current wany is:

Setting base path:

Add the docker variable ROOT_URL

`-e 'ROOT_URL'='http://localhost/tdarr'`

Example proxy pass in nginx config:

`proxy_pass http://192.168.1.50:8265/tdarr/;`

**Comment by HaveAGitGat** [comment]
Another user has been playing around with it to get it working, I've updated the wiki.

**Comment by Apezdr** [comment]
[https://docs.tdarr.io/docs/installation/extra](https://docs.tdarr.io/docs/installation/extra)
@HaveAGitGat the guide on the Extra page has this for apache2

```
<Location "/test/abc/testtdarr/">
    ProxyPass "http://127.0.0.1:8265/"
    ProxyPassReverse "/"
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For %{HTTP_PROXY_ADD_X_FORWARDED_FOR}s
</Location>
```

When using this it will load the "Connecting..." page but it will fail to establish a socketio connection. It must be adjusted so that `ProxyPass` is `"http://127.0.0.1:8265"` without the slash at the end seems to fix it.
