### ISSUE TITLE
Video file is detected as an audio file

### ISSUE THREAD

**Issue by fletchto99** [HaveAGitGat/Tdarr#94]
I'm trying to transcode my family video library. The newer stuff from phones transcoded fine but older videos are being detected as audio files.

![654f8d936b48b04188590ee9490782a3](https://user-images.githubusercontent.com/718681/70385413-41c62380-194a-11ea-9dca-f511a6952e3e.png)

As you can see there is an mjpeg video stream but the `fileMedium` is reporting `audio` thus preventing transcoding from occurring.

**Comment by HaveAGitGat** [comment]
@fletchto99  sorry about that. Someone was recently  having the opposite issue of audio files being detected as video due to the audio files having mjpeg covert art which I fixed but has obviously caused issues for you.

https://github.com/HaveAGitGat/Tdarr/issues/88

I’ll have to come up with a different solution for differentiating audio/video files which both have mjpeg video streams and (any) audio streams.

**Comment by HaveAGitGat** [comment]
Fixed in 1.102

**Comment by ansuz07** [comment]
Any word on when you might push 1.102 to the docker hub?

**Comment by HaveAGitGat** [comment]
@ansuz07 @fletchto99 

Apologies, I had to take some time off from this project. I'll push the update this weekend.

**Comment by ansuz07** [comment]
No worries and no need to apologize. I really appreciate the project and the work you’ve put in.

**Comment by HaveAGitGat** [comment]
Thanks, just pushed the update. It now relies on exiftool to determine whether a file is a video/audio. Should fix the issue.
