### ISSUE TITLE
Please finally fix notify flow

### ISSUE THREAD

**Issue by CurlyFlow** [HaveAGitGat/Tdarr#975]
To make it short, the sonarr part is working fine, the radarr one doesnt work.

It never did since you added it.. i think its very important because i dont want to redownload things just because radarr thinks it has a "old" file...

**Comment by HaveAGitGat** [comment]
Thanks, last time I tried this it worked fine for me. You can see here the same method is used for both radarr and sonarr:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.ts#L115

Which radarr and sonarr versions are you using?

**Comment by dennix85** [comment]
No issues here neither, i do also file rename incl {avcodec} (soundcodec} since day 1 i use notify radarr and sonarr, 
are you sure the api key is correct ? 
And is it the last step of the entire flow ? 
(i use binhex containers for the arrs btw)

**Comment by Marnalas** [comment]
I had some issues with the notify plugin but only on some specific movies. I rewrote this plugin to make it more robust then opened a pull request some time ago : https://github.com/HaveAGitGat/Tdarr_Plugins/pull/600
The version I submitted fixed all the inconsistences I observed in my library. Might be worth a try.

One thing I added was to try to get the id of the movie using the inputFileObj._id (current file name) if the plugin fails with the originalLibraryFile._id (original file name).

**Comment by dennix85** [comment]
your radarr errors out, its a communication issue with your radarr it should look almost the same as the sonarr one
really check radarr, firewall settings and portmappings on your containers 
Have you checked your radarr logs if there are errors in there ? 
![image](https://github.com/HaveAGitGat/Tdarr/assets/129799653/e24ab9b1-0afb-4910-95ed-7d917225e2d6)

**Comment by Marnalas** [comment]
I remember investigating this issue (before I made the modifications on the plugin). I imported the open API file on Postman and made some tests there.

1. Any problem on the URL, port or protocol (and I suppose firewall settings) gets you an ECONNREFUSED error in return. Not the problem here.

2. If the api-key is incorrect you get an empty body response :

![image](https://github.com/HaveAGitGat/Tdarr/assets/11569431/0b26aed2-3660-4b6d-88e1-4739924a9b18)

3. If the movie's title is not found : 

![image](https://github.com/HaveAGitGat/Tdarr/assets/11569431/6a167304-5e88-4fe0-82aa-9488bfc66692)

4. At the time I also confirmed through Postman (so nothing to do with the plugin) that sometimes everything is correct, but Radarr just doesn't find the movie using the original name.

Given the error  : 

1. can be eliminated right away.
2. is very possible so I suggest you check your api-key once more.
3. is a possibility but you won't be able to acertain it without using an external tool that shows the response provided by Radarr's API. You can use their Swagger if you don't want to install Postman : https://radarr.video/docs/api/
4. is a possibility but it wouldn't happen on ALL your movies.

**Comment by Marnalas** [comment]
Am I correct in assuming that you use two separate libraries for your movies and series and that the movie library uses another flow which has the Radarr configuration ?

Did you also check your API key for this flow ?

**Comment by Marnalas** [comment]
I don't see anything there that would cause the issue. That being said, since this plugin is used by lots of people, and it's obviously working for most of us, the problem is still probably on your side.
At that point I can only tell you to try to get more information using Postman or Radarr's API Swagger https://radarr.video/docs/api/ (if your Radarr instance is externally accessible, which I can't recommend) or wait for the pull request containing my modifications to be approved then try again by using the v2.0.0 of this plugin (even though there is no guarantee that it would fix your problem).

**Comment by HaveAGitGat** [comment]
@CurlyFlow still need to check some things but you can try out their changes by adding the js file to your local plugins at: 

FlowPlugins/LocalFlowPlugins/tools/notifyRadarrOrSonarr/2.0.0/index.js

Let us know if it works for you

**Comment by Marnalas** [comment]
You can find the file here : https://github.com/HaveAGitGat/Tdarr_Plugins/pull/600/files
There are two files, be sure to take the one with .js extension (not .ts).

> i somehow manually querryd radarr, and it would work with the new name, but not the old. Why i dont know. But a fix would be, try normal, if not working, try new name?

This might happen if, somehow, Radarr detects the name change before the notify plugin is executed. Trying with the new name is one of the changes I implemented. So if it's the root of your issue, first of all my modifications should work for you and you should see something along those lines it in the logs 

> Didn't find movie with a file named '<originalName>' in Radarr.
> Found movie <movieId> with a file named  '<newName>'

**Comment by HaveAGitGat** [comment]
Yes my suggestion was to put it in the LocalFlowPlugins folder (you might need to create this) as it’s not coming from the community plugins repo atm but you can put it in either - plugins in CommunityFlowPlugins can be overwritten by any future updates but LocalFlowPlugins is just your own plugins.

Yes once you’ve added it there you need to then select the new plugin version in the webUI and add it to the flow (refresh the page), it will be on the right hand side bar in the default position. The old 1.0.0 version will be at the very bottom of the sidebar if you still need to use it.

**Comment by HaveAGitGat** [comment]
E.g. tab here:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/dd847992-f88a-4c42-ac2d-ecbb15974c05)'

You can confirm the version by clicking on it:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/fe07f37b-8e3b-4602-ae27-9106449fd189)

Old versions will appear at bottom if you have both 1.0.0 and 2.0.0 in LocalFlowPlugins:
(I just added some for example purposes)
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/f8cda1b0-a555-4ca3-bc0e-74c9b0f0d76f)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/2ded0175-ed2d-44eb-9b96-a10324881c03)

**Comment by Marnalas** [comment]
Yup, from the logs it looks like my modifications are there. 
Only one attempt has been made with the original file name. The plug-in only makes another attempt with the current file name if it's different from the original one.
So your problem is somewhere else.
Do you have any other mechanism renaming your files besides tdarr?

**Comment by Marnalas** [comment]
Ah no, didn't see it.

I follow the trash guides naming schemes https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/. My file names look like this : Dune (2021) {imdb-tt1160419} [Bluray-1080p][TrueHD Atmos 7.1][FR+EN][h265]-FoX.mkv
From what I saw, the names you use are shorter than mines. The special characters I saw some issues with at times are interrogation points for example.

There is something I don't understand in what you wrote in your edit. You say that the file name showed in the plugin logs (Alien Outbreak [DE+EN] Remux-1080p) is not the correct one known by Radarr. That implies that something changed the name at some point. Can you give us more details about that ?

In my situation this is what happens : 
1. Radarr grabs the fileit and names it according to its naming policy
3. Tdarr detects the new file (my librairies are set up with folder watch)
4. Tdarr does its thing (transcodes, stream filtering, etc.)
5. Tdarr notifies Radarr
6. I use a plugin I wrote for Tdarr to update the file name according to Radarr naming policy (https://github.com/HaveAGitGat/Tdarr_Plugins/pull/589)
7. Tdarr notifies Radarr of the name change

No renaming happens between steps 2 and 5. From what you're describing, it looks like you have some other stuff happening that changes the name outside of Tdarr. I know you already said that it's not the case but I don't get how Tdarr could have "an old name" without the name being changed at some point.

**Comment by Marnalas** [comment]
Yeah I force the container to mkv and also transcode video+audio (which impacts the files names). I have two Radarr instances, each linked to its own Tdarr library. Both of them are updated to the last version automatically, right now they are v5.3.6.8612.

What you just wrote raises a lot of questions. But handling that here will be complicated. I think a discord conversation/screen share will be needed. The easiest way to organise that would be for you to join the Tdarr discord : https://discord.com/invite/q8AcZWQ. Contact me in the help-chat channel, by tagging "Enro Marnalas".

**Comment by Marnalas** [comment]
For anybody reading this.

@CurlyFlow shared his screen and we investigated. I can say for sure that it's not a Tdarr/Tdarr plugin issue. The problem comes from the Radarr API "parse" endpoint used to get the movieId. We queried it directly with curl and, I have no idea why, it just refused to find the movies even when the file name was correct. We checked everything we could think of (cultural context issues with some characters decoding, etc.) but even with a file name reduced to "eins.mp4" the parse endpoint still refused to work as intended.

We hang up on the conclusion that maybe it's related to CurlyFlow's installation being quite old and having migrated through many versions, maybe it's the fact that he has lots of content, maybe it's a combination of everything, etc. Short version: we don't know.

CurlyFlow is gonna try to do a fresh install with a few movies and check if it works.
On my side I just think that the "parse" endpoint is a pretty inefficient way to query for the movieId. It uses the file name which, for a lot of people who follow the Plex/Jellyfin/Emby naming recommendations, is quite long and contains lots of special characters that are not friendly as an HTTP query parameter. I'm gonna look into proposing a modified version of the notify flow plugin using the "movieLookup" endpoints instead.

**Comment by supersnellehenk** [comment]
@Marnalas FYI, I switched from the movieLookup endpoint to the parse endpoint (in combination with [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)) to have Radarr be in charge of trying to find the file. Especially with larger installs the movieLookup response could be quite large.

**Comment by Marnalas** [comment]
@supersnellehenk Thank you for your message. I'll try to play with the moovieLookup endpoints in postman and try to determine how to use it best to not have this large response problem. I do agree with you that Radarr should be in charge of finding the movie.
Also, thank you for your work on this plugin. I used it for a while before I modified it and it's been an important part of my flow.

More details on what I intend to do :
The main moovieLookup endpoint I'm thinking about is the one accepting an imdbId parameter. This endpoint shouldn't return multiple results (so the response shouldn't be any larger than it is for the parse endpoint). My intention is to try to get the imdb id from the file name or the file path using a regex then try to get the movieId with that.
I'll keep the parse endpoint as a fallback method if no imdb code has been found or if it failed to find the movieID. At least we know that it works for a majority of people (myself included).

**Comment by Marnalas** [comment]
Ok, just got confirmation from @CurlyFlow that the latest modifications I made in the PR https://github.com/HaveAGitGat/Tdarr_Plugins/pull/600 solved his issue. The notify plugin is now able to find the movieId throught the Lookup?term=imdb:<imdbId> endpoint (for booth Radarr and Sonarr).

```
2024-03-31T22:08:22.807Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:Using cached scan results
2024-03-31T22:08:22.807Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:Loaded plugin inputs: {
2024-03-31T22:08:22.807Z "arr": "radarr",
2024-03-31T22:08:22.807Z "arr_api_key": "X",
2024-03-31T22:08:22.807Z "arr_host": "X"
2024-03-31T22:08:22.807Z }
2024-03-31T22:08:22.807Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:Going to force scan
2024-03-31T22:08:22.807Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:Refreshing radarr...
2024-03-31T22:08:22.807Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:Movie '2859' found for imdb 'tt0318649'
2024-03-31T22:08:22.807Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:✔ Movie '2859' refreshed in radarr.
2024-03-31T22:08:22.807Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:Plugin run complete
2024-03-31T22:08:22.808Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:{"_id":"/mnt/user/Archiv/Filme/Sahara (2005) {imdb-tt0318649}/Sahara [DE] Remux-1080p.mp4","outputNumber":1,"variables":{"flowFailed":false}}
2024-03-31T22:08:22.808Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:No next plugin
2024-03-31T22:08:22.808Z tC8xSEHHu:Node[MyInternalNode]:Worker[neat-newt]:Requesting Tdarr Server to scan file
```

**Comment by Marnalas** [comment]
> Yes, its working fine! I dont know how it works, but is it possible to hide this issue (because there is many personal information here) after it has been added to tdarr?

You should edit your messages and remove any personal information. I'll do it my messages.
