### ISSUE TITLE
[Feature] Disable cache?

### ISSUE THREAD

**Issue by CurlyFlow** [HaveAGitGat/Tdarr#984]
Hi,
i would like to disable the cache for some librarys because the files are already on a cache drive so that doesnt really make sense in my setup. After they are processed they get moved.

Is that possible to add as a feature?

**Comment by HaveAGitGat** [comment]
Hi @CurlyFlow, not 100% sure what you're asking but Tdarr needs a cache location to temporarily work on files. This location can be anywhere and can be set in the Library settings `Transcode cache` option. So you can put it on your cache drive or wherever else. `Cache from` Tdarr's perspective just means `directory to temporarily work on files` and is unrelated to any OS cache features.

**Comment by HaveAGitGat** [comment]
Sorry still not sure what you mean. If you're wanting to have the cache folder on the same as your cache disk then can place it there. The Tdarr transcode cache folder is essential as it's temporary folder for Tdarr to work on files. It's not right to have this done in the original file location as there could be all sorts of conflicts such as file name issues, locked files, interference from other applications etc.

@supersnellehenk are you familiar with Curly's use case here?

It maybe sounds like you're wanting to put the file in a specific location after processing for archiving? You can do that with a flow e.g:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/2793aa2c-825b-41a9-8c7c-65520b0a39df)

**Comment by HaveAGitGat** [comment]
@CurlyFlow if you're able to re-word your request to make it clearer then can have another look but seems like you're misunderstanding what the Tdarr cache is. It's a directory for Tdarr to work on files temporarily and it needs to be somewhere, it can't be disabled.

For example:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/e1fb4175-161e-437c-91b4-ae86fca15159)

In flow route 1: The file will be processed in the Tdarr cache and moved back to the library. You can put the cache on the same disk/drive as the source file so that when the file is moved back to the source it happens *instantly*.

In flow route 2: File does not need to processed, cache is not used. Maybe you thought the cache is still being used here but, to clarify, it's not.
