### ISSUE TITLE
Use iOS device as node

### ISSUE THREAD

**Issue by memoryracer** [HaveAGitGat/Tdarr#989]
**Is your feature request related to a problem? Please describe.**
As an individual I want to transcode large quantities of media without purchasing extra hardware, because I already own powerful devices with great transcoding capabilities: my iPhone or iPad

**Describe the solution you'd like**
Maybe it's not that hard to port the current macOS app to iOS? In my opinion, the server app is not that important for iOS, but using it as node could help out people on a small budget.

**Describe alternatives you've considered**
CPU transcodig on my server, but it's slow

**Additional context**
I found this reddit post: https://www.reddit.com/r/Tdarr/comments/11s145q/adding_an_ipadiphone_as_a_node_to_run_transcoding/

**Comment by HaveAGitGat** [comment]
The issue is Tdarr uses a lot of dependencies which aren't available for iOS, there'd potentially need to be a full re-write of the Node and I don't think in practice many people would use it due to slow performance. Messaged Mr-Ababe late year for an update on his project but don't think he ever finished it. If you come across a network API for FFmpeg on iOS then could potentially make a Tdarr flow plugin to use.
